// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module master_ip_uart_to_byte (
        uart_to_coordinates_count_V_i,
        uart_to_coordinates_count_V_o,
        uart_to_coordinates_count_V_o_ap_vld,
        uart_to_coordinates_previous_input_V_i,
        uart_to_coordinates_previous_input_V_o,
        uart_to_coordinates_previous_input_V_o_ap_vld,
        uart_to_coordinates_current_input_V_read,
        uart_to_coordinates_uart_state_V_i,
        uart_to_coordinates_uart_state_V_o,
        uart_to_coordinates_uart_state_V_o_ap_vld,
        uart_to_coordinates_next_out_byte_V_i,
        uart_to_coordinates_next_out_byte_V_o,
        uart_to_coordinates_next_out_byte_V_o_ap_vld,
        uart_to_coordinates_current_out_byte_V_read,
        ap_return_0,
        ap_return_1
);

parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_true = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv16_546 = 16'b10101000110;
parameter    ap_const_lv16_4E2 = 16'b10011100010;
parameter    ap_const_lv16_FAED = 16'b1111101011101101;
parameter    ap_const_lv4_F = 4'b1111;
parameter    ap_const_lv4_E = 4'b1110;
parameter    ap_const_lv4_D = 4'b1101;
parameter    ap_const_lv4_C = 4'b1100;
parameter    ap_const_lv4_B = 4'b1011;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_const_lv5_1E = 5'b11110;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv4_9 = 4'b1001;
parameter    ap_const_lv16_37DC = 16'b11011111011100;

input  [15:0] uart_to_coordinates_count_V_i;
output  [15:0] uart_to_coordinates_count_V_o;
output   uart_to_coordinates_count_V_o_ap_vld;
input  [0:0] uart_to_coordinates_previous_input_V_i;
output  [0:0] uart_to_coordinates_previous_input_V_o;
output   uart_to_coordinates_previous_input_V_o_ap_vld;
input  [0:0] uart_to_coordinates_current_input_V_read;
input  [3:0] uart_to_coordinates_uart_state_V_i;
output  [3:0] uart_to_coordinates_uart_state_V_o;
output   uart_to_coordinates_uart_state_V_o_ap_vld;
input  [7:0] uart_to_coordinates_next_out_byte_V_i;
output  [7:0] uart_to_coordinates_next_out_byte_V_o;
output   uart_to_coordinates_next_out_byte_V_o_ap_vld;
input  [7:0] uart_to_coordinates_current_out_byte_V_read;
output  [0:0] ap_return_0;
output  [7:0] ap_return_1;

reg[15:0] uart_to_coordinates_count_V_o;
reg uart_to_coordinates_count_V_o_ap_vld;
reg[0:0] uart_to_coordinates_previous_input_V_o;
reg uart_to_coordinates_previous_input_V_o_ap_vld;
reg[3:0] uart_to_coordinates_uart_state_V_o;
reg uart_to_coordinates_uart_state_V_o_ap_vld;
reg[7:0] uart_to_coordinates_next_out_byte_V_o;
reg uart_to_coordinates_next_out_byte_V_o_ap_vld;
reg   [0:0] storemerge_phi_fu_155_p4;
wire   [0:0] tmp_fu_222_p2;
wire   [0:0] uart_to_coordinates_current_in_1_read_fu_86_p2;
wire   [0:0] or_cond4_fu_699_p2;
reg   [7:0] uart_to_coordinates_current_ou_1_phi_fu_167_p4;
wire   [0:0] tmp_1_fu_228_p2;
wire   [0:0] tmp_24_fu_306_p2;
wire   [0:0] or_cond3_fu_574_p2;
wire   [7:0] uart_to_coordinates_current_ou_fu_641_p3;
reg   [0:0] p_s_phi_fu_177_p4;
wire   [0:0] uart_to_coordinates_uart_state_2_fu_622_p2;
wire   [15:0] uart_to_coordinates_count_V_wr_fu_480_p3;
wire   [15:0] uart_to_coordinates_count_V_wr_1_fu_666_p3;
wire   [15:0] grp_fu_215_p2;
wire   [0:0] grp_fu_196_p2;
wire   [15:0] grp_fu_208_p2;
wire   [0:0] grp_fu_202_p2;
wire   [0:0] tmp_2_fu_693_p2;
wire   [0:0] uart_to_coordinates_previous_i_1_fu_497_p3;
wire   [0:0] uart_to_coordinates_previous_i_2_fu_675_p3;
wire   [3:0] uart_to_coordinates_uart_state_1_fu_522_p3;
wire   [3:0] uart_to_coordinates_uart_state_4_fu_684_p3;
wire   [7:0] uart_to_coordinates_next_out_b_1_fu_555_p2;
wire   [0:0] grp_fu_184_p2;
wire   [0:0] grp_fu_190_p2;
wire   [0:0] sel_tmp9_fu_610_p2;
wire   [0:0] sel_tmp4_fu_592_p2;
wire   [0:0] tmp_12_fu_240_p2;
wire   [0:0] tmp_10_fu_234_p2;
wire   [0:0] tmp_15_fu_252_p2;
wire   [0:0] tmp_14_fu_246_p2;
wire   [0:0] tmp_17_fu_264_p2;
wire   [0:0] tmp_16_fu_258_p2;
wire   [0:0] tmp_19_fu_276_p2;
wire   [0:0] tmp_18_fu_270_p2;
wire   [0:0] tmp_21_fu_288_p2;
wire   [0:0] tmp_20_fu_282_p2;
wire   [0:0] tmp_23_fu_300_p2;
wire   [0:0] tmp_22_fu_294_p2;
wire   [4:0] lhs_V_1_i_cast_fu_318_p1;
wire   [4:0] r_V_4_fu_322_p2;
wire   [4:0] tmp_56_i_cast_fu_340_p1;
wire   [4:0] tmp_57_i_fu_344_p2;
wire   [31:0] tmp_56_i_fu_336_p1;
wire  signed [31:0] tmp_60_i_fu_356_p1;
wire   [4:0] tmp_63_i_cast_fu_370_p1;
wire   [31:0] tmp_63_i_fu_366_p1;
wire   [4:0] tmp_58_i_fu_350_p2;
wire   [31:0] tmp_61_i_fu_360_p2;
wire   [0:0] tmp_25_fu_328_p3;
wire   [7:0] tmp_5_fu_386_p1;
wire   [7:0] tmp_26_fu_390_p1;
wire   [4:0] tmp_65_i_fu_374_p2;
wire   [31:0] tmp_68_i_fu_380_p2;
wire   [7:0] tmp_11_fu_408_p1;
wire   [7:0] tmp_27_fu_412_p1;
wire   [0:0] tmp_i1_fu_312_p2;
wire   [0:0] sel_tmp_i_fu_424_p2;
wire   [0:0] sel_tmp1_i_fu_430_p2;
wire   [15:0] sel_tmp2_v_i_cast_cast_fu_436_p3;
wire   [0:0] sel_tmp3_i_fu_450_p2;
wire   [0:0] tmp1_fu_462_p2;
wire   [0:0] sel_tmp6_i_fu_468_p2;
wire   [0:0] sel_tmp4_i_fu_456_p2;
wire   [0:0] tmp_13_fu_474_p2;
wire   [15:0] sel_tmp2_i_fu_444_p2;
wire   [0:0] sel_tmp13_i_fu_489_p3;
wire   [3:0] tmp_70_i_fu_402_p2;
wire   [3:0] newSel_fu_506_p3;
wire   [3:0] newSel1_fu_514_p3;
wire   [7:0] r_V_fu_394_p3;
wire   [7:0] r_V_1_fu_416_p3;
wire   [7:0] newSel3_fu_531_p3;
wire   [7:0] newSel4_fu_539_p3;
wire   [7:0] newSel5_fu_547_p3;
wire   [0:0] tmp_9_fu_562_p2;
wire   [0:0] tmp_3_fu_568_p2;
wire   [0:0] sel_tmp3_fu_586_p2;
wire   [0:0] uart_to_coordinates_current_in_fu_580_p2;
wire   [0:0] tmp2_fu_604_p2;
wire   [0:0] sel_tmp_fu_616_p2;
wire   [7:0] sel_tmp1_fu_633_p3;
wire   [15:0] newSel6_fu_650_p3;
wire   [15:0] newSel7_fu_658_p3;
wire   [0:0] sel_tmp7_fu_598_p2;
wire   [3:0] uart_to_coordinates_uart_state_3_fu_629_p1;
reg    ap_sig_bdd_480;




always @ (tmp_fu_222_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or or_cond3_fu_574_p2 or uart_to_coordinates_uart_state_2_fu_622_p2) begin
    if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == tmp_24_fu_306_p2) & ~(ap_const_lv1_0 == or_cond3_fu_574_p2))) begin
        p_s_phi_fu_177_p4 = uart_to_coordinates_uart_state_2_fu_622_p2;
    end else if ((~(tmp_fu_222_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp_1_fu_228_p2) | (ap_const_lv1_0 == tmp_24_fu_306_p2) | (ap_const_lv1_0 == or_cond3_fu_574_p2))) begin
        p_s_phi_fu_177_p4 = ap_const_lv1_0;
    end else begin
        p_s_phi_fu_177_p4 = 'bx;
    end
end

always @ (tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or ap_sig_bdd_480) begin
    if (~(tmp_fu_222_p2 == ap_const_lv1_0)) begin
        if (ap_sig_bdd_480) begin
            storemerge_phi_fu_155_p4 = ap_const_lv1_0;
        end else if (~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2)) begin
            storemerge_phi_fu_155_p4 = ap_const_lv1_1;
        end else begin
            storemerge_phi_fu_155_p4 = 'bx;
        end
    end else begin
        storemerge_phi_fu_155_p4 = 'bx;
    end
end

always @ (uart_to_coordinates_count_V_i or tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or or_cond4_fu_699_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or or_cond3_fu_574_p2 or uart_to_coordinates_count_V_wr_fu_480_p3 or uart_to_coordinates_count_V_wr_1_fu_666_p3 or grp_fu_215_p2 or grp_fu_196_p2 or grp_fu_208_p2 or grp_fu_202_p2 or tmp_2_fu_693_p2) begin
    if ((~(tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & (ap_const_lv1_0 == or_cond4_fu_699_p2))) begin
        uart_to_coordinates_count_V_o = ap_const_lv16_0;
    end else if ((((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == grp_fu_202_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_202_p2)) | (~(tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == or_cond4_fu_699_p2)))) begin
        uart_to_coordinates_count_V_o = ap_const_lv16_1;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_196_p2))) begin
        uart_to_coordinates_count_V_o = grp_fu_208_p2;
    end else if ((((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == grp_fu_196_p2)) | (~(tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & (ap_const_lv1_0 == tmp_2_fu_693_p2)))) begin
        uart_to_coordinates_count_V_o = grp_fu_215_p2;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == tmp_24_fu_306_p2) & ~(ap_const_lv1_0 == or_cond3_fu_574_p2))) begin
        uart_to_coordinates_count_V_o = uart_to_coordinates_count_V_wr_1_fu_666_p3;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == tmp_24_fu_306_p2))) begin
        uart_to_coordinates_count_V_o = uart_to_coordinates_count_V_wr_fu_480_p3;
    end else begin
        uart_to_coordinates_count_V_o = uart_to_coordinates_count_V_i;
    end
end

always @ (tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or or_cond4_fu_699_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or or_cond3_fu_574_p2 or grp_fu_196_p2 or grp_fu_202_p2 or tmp_2_fu_693_p2) begin
    if (((~(tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & (ap_const_lv1_0 == or_cond4_fu_699_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == tmp_24_fu_306_p2) & ~(ap_const_lv1_0 == or_cond3_fu_574_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == tmp_24_fu_306_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == grp_fu_196_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_196_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == grp_fu_202_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_202_p2)) | (~(tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == or_cond4_fu_699_p2)) | (~(tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & (ap_const_lv1_0 == tmp_2_fu_693_p2)))) begin
        uart_to_coordinates_count_V_o_ap_vld = ap_const_logic_1;
    end else begin
        uart_to_coordinates_count_V_o_ap_vld = ap_const_logic_0;
    end
end

always @ (uart_to_coordinates_current_out_byte_V_read or tmp_fu_222_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or or_cond3_fu_574_p2 or uart_to_coordinates_current_ou_fu_641_p3) begin
    if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == tmp_24_fu_306_p2) & ~(ap_const_lv1_0 == or_cond3_fu_574_p2))) begin
        uart_to_coordinates_current_ou_1_phi_fu_167_p4 = uart_to_coordinates_current_ou_fu_641_p3;
    end else if ((~(tmp_fu_222_p2 == ap_const_lv1_0) | ~(ap_const_lv1_0 == tmp_1_fu_228_p2) | (ap_const_lv1_0 == tmp_24_fu_306_p2) | (ap_const_lv1_0 == or_cond3_fu_574_p2))) begin
        uart_to_coordinates_current_ou_1_phi_fu_167_p4 = uart_to_coordinates_current_out_byte_V_read;
    end else begin
        uart_to_coordinates_current_ou_1_phi_fu_167_p4 = 'bx;
    end
end

always @ (uart_to_coordinates_next_out_byte_V_i or tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or grp_fu_196_p2 or grp_fu_202_p2 or uart_to_coordinates_next_out_b_1_fu_555_p2) begin
    if ((((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_196_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_202_p2)))) begin
        uart_to_coordinates_next_out_byte_V_o = ap_const_lv8_0;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == tmp_24_fu_306_p2))) begin
        uart_to_coordinates_next_out_byte_V_o = uart_to_coordinates_next_out_b_1_fu_555_p2;
    end else begin
        uart_to_coordinates_next_out_byte_V_o = uart_to_coordinates_next_out_byte_V_i;
    end
end

always @ (tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or grp_fu_196_p2 or grp_fu_202_p2) begin
    if ((((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == tmp_24_fu_306_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_196_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_202_p2)))) begin
        uart_to_coordinates_next_out_byte_V_o_ap_vld = ap_const_logic_1;
    end else begin
        uart_to_coordinates_next_out_byte_V_o_ap_vld = ap_const_logic_0;
    end
end

always @ (uart_to_coordinates_previous_input_V_i or storemerge_phi_fu_155_p4 or tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or or_cond4_fu_699_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or or_cond3_fu_574_p2 or grp_fu_196_p2 or grp_fu_202_p2 or uart_to_coordinates_previous_i_1_fu_497_p3 or uart_to_coordinates_previous_i_2_fu_675_p3) begin
    if (((~(tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2)) | (~(tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == or_cond4_fu_699_p2)))) begin
        uart_to_coordinates_previous_input_V_o = storemerge_phi_fu_155_p4;
    end else if ((((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == grp_fu_202_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_202_p2)))) begin
        uart_to_coordinates_previous_input_V_o = ap_const_lv1_1;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_196_p2))) begin
        uart_to_coordinates_previous_input_V_o = ap_const_lv1_0;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == tmp_24_fu_306_p2) & ~(ap_const_lv1_0 == or_cond3_fu_574_p2))) begin
        uart_to_coordinates_previous_input_V_o = uart_to_coordinates_previous_i_2_fu_675_p3;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == tmp_24_fu_306_p2))) begin
        uart_to_coordinates_previous_input_V_o = uart_to_coordinates_previous_i_1_fu_497_p3;
    end else begin
        uart_to_coordinates_previous_input_V_o = uart_to_coordinates_previous_input_V_i;
    end
end

always @ (tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or or_cond4_fu_699_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or or_cond3_fu_574_p2 or grp_fu_196_p2 or grp_fu_202_p2) begin
    if (((~(tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == tmp_24_fu_306_p2) & ~(ap_const_lv1_0 == or_cond3_fu_574_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == tmp_24_fu_306_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_196_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == grp_fu_202_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_202_p2)) | (~(tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == or_cond4_fu_699_p2)))) begin
        uart_to_coordinates_previous_input_V_o_ap_vld = ap_const_logic_1;
    end else begin
        uart_to_coordinates_previous_input_V_o_ap_vld = ap_const_logic_0;
    end
end

always @ (uart_to_coordinates_uart_state_V_i or tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or or_cond4_fu_699_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or or_cond3_fu_574_p2 or grp_fu_196_p2 or grp_fu_202_p2 or uart_to_coordinates_uart_state_1_fu_522_p3 or uart_to_coordinates_uart_state_4_fu_684_p3) begin
    if ((~(tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == or_cond4_fu_699_p2))) begin
        uart_to_coordinates_uart_state_V_o = ap_const_lv4_1;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == grp_fu_202_p2))) begin
        uart_to_coordinates_uart_state_V_o = ap_const_lv4_0;
    end else if ((((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_196_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_202_p2)))) begin
        uart_to_coordinates_uart_state_V_o = ap_const_lv4_2;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == tmp_24_fu_306_p2) & ~(ap_const_lv1_0 == or_cond3_fu_574_p2))) begin
        uart_to_coordinates_uart_state_V_o = uart_to_coordinates_uart_state_4_fu_684_p3;
    end else if (((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == tmp_24_fu_306_p2))) begin
        uart_to_coordinates_uart_state_V_o = uart_to_coordinates_uart_state_1_fu_522_p3;
    end else begin
        uart_to_coordinates_uart_state_V_o = uart_to_coordinates_uart_state_V_i;
    end
end

always @ (tmp_fu_222_p2 or uart_to_coordinates_current_in_1_read_fu_86_p2 or or_cond4_fu_699_p2 or tmp_1_fu_228_p2 or tmp_24_fu_306_p2 or or_cond3_fu_574_p2 or grp_fu_196_p2 or grp_fu_202_p2) begin
    if ((((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == tmp_24_fu_306_p2) & ~(ap_const_lv1_0 == or_cond3_fu_574_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == tmp_24_fu_306_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_196_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & (ap_const_lv1_0 == grp_fu_202_p2)) | ((tmp_fu_222_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == tmp_1_fu_228_p2) & ~(ap_const_lv1_0 == grp_fu_202_p2)) | (~(tmp_fu_222_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & ~(ap_const_lv1_0 == or_cond4_fu_699_p2)))) begin
        uart_to_coordinates_uart_state_V_o_ap_vld = ap_const_logic_1;
    end else begin
        uart_to_coordinates_uart_state_V_o_ap_vld = ap_const_logic_0;
    end
end

assign ap_return_0 = p_s_phi_fu_177_p4;

assign ap_return_1 = uart_to_coordinates_current_ou_1_phi_fu_167_p4;


always @ (uart_to_coordinates_current_in_1_read_fu_86_p2 or or_cond4_fu_699_p2) begin
    ap_sig_bdd_480 = ((ap_const_lv1_0 == uart_to_coordinates_current_in_1_read_fu_86_p2) & (ap_const_lv1_0 == or_cond4_fu_699_p2));
end

assign grp_fu_184_p2 = (uart_to_coordinates_count_V_i < ap_const_lv16_546? 1'b1: 1'b0);

assign grp_fu_190_p2 = (uart_to_coordinates_count_V_i > ap_const_lv16_4E2? 1'b1: 1'b0);

assign grp_fu_196_p2 = (uart_to_coordinates_count_V_i > ap_const_lv16_546? 1'b1: 1'b0);

assign grp_fu_202_p2 = (grp_fu_184_p2 & grp_fu_190_p2);

assign grp_fu_208_p2 = ($signed(uart_to_coordinates_count_V_i) + $signed(ap_const_lv16_FAED));

assign grp_fu_215_p2 = (uart_to_coordinates_count_V_i + ap_const_lv16_1);

assign lhs_V_1_i_cast_fu_318_p1 = uart_to_coordinates_uart_state_V_i;

assign newSel1_fu_514_p3 = ((sel_tmp1_i_fu_430_p2[0:0] === 1'b1) ? tmp_70_i_fu_402_p2 : uart_to_coordinates_uart_state_V_i);

assign newSel3_fu_531_p3 = ((sel_tmp6_i_fu_468_p2[0:0] === 1'b1) ? r_V_fu_394_p3 : ap_const_lv8_0);

assign newSel4_fu_539_p3 = ((sel_tmp1_i_fu_430_p2[0:0] === 1'b1) ? r_V_1_fu_416_p3 : ap_const_lv8_0);

assign newSel5_fu_547_p3 = ((tmp_13_fu_474_p2[0:0] === 1'b1) ? newSel3_fu_531_p3 : newSel4_fu_539_p3);

assign newSel6_fu_650_p3 = ((sel_tmp9_fu_610_p2[0:0] === 1'b1) ? ap_const_lv16_1 : grp_fu_208_p2);

assign newSel7_fu_658_p3 = ((sel_tmp4_fu_592_p2[0:0] === 1'b1) ? grp_fu_215_p2 : ap_const_lv16_1);

assign newSel_fu_506_p3 = ((sel_tmp6_i_fu_468_p2[0:0] === 1'b1) ? tmp_70_i_fu_402_p2 : ap_const_lv4_0);

assign or_cond3_fu_574_p2 = (tmp_9_fu_562_p2 & tmp_3_fu_568_p2);

assign or_cond4_fu_699_p2 = (uart_to_coordinates_previous_input_V_i & tmp_2_fu_693_p2);

assign r_V_1_fu_416_p3 = ((tmp_25_fu_328_p3[0:0] === 1'b1) ? tmp_11_fu_408_p1 : tmp_27_fu_412_p1);

assign r_V_4_fu_322_p2 = ($signed(ap_const_lv5_1E) + $signed(lhs_V_1_i_cast_fu_318_p1));

assign r_V_fu_394_p3 = ((tmp_25_fu_328_p3[0:0] === 1'b1) ? tmp_5_fu_386_p1 : tmp_26_fu_390_p1);

assign sel_tmp13_i_fu_489_p3 = ((sel_tmp4_i_fu_456_p2[0:0] === 1'b1) ? uart_to_coordinates_current_input_V_read : uart_to_coordinates_previous_input_V_i);

assign sel_tmp1_fu_633_p3 = ((sel_tmp_fu_616_p2[0:0] === 1'b1) ? uart_to_coordinates_next_out_byte_V_i : uart_to_coordinates_current_out_byte_V_read);

assign sel_tmp1_i_fu_430_p2 = (grp_fu_196_p2 & sel_tmp_i_fu_424_p2);

assign sel_tmp2_i_fu_444_p2 = (uart_to_coordinates_count_V_i + sel_tmp2_v_i_cast_cast_fu_436_p3);

assign sel_tmp2_v_i_cast_cast_fu_436_p3 = ((sel_tmp1_i_fu_430_p2[0:0] === 1'b1) ? ap_const_lv16_FAED : ap_const_lv16_1);

assign sel_tmp3_fu_586_p2 = (grp_fu_196_p2 ^ ap_const_lv1_1);

assign sel_tmp3_i_fu_450_p2 = (grp_fu_202_p2 ^ ap_const_lv1_1);

assign sel_tmp4_fu_592_p2 = (uart_to_coordinates_current_input_V_read & sel_tmp3_fu_586_p2);

assign sel_tmp4_i_fu_456_p2 = (tmp_i1_fu_312_p2 & sel_tmp3_i_fu_450_p2);

assign sel_tmp6_i_fu_468_p2 = (tmp1_fu_462_p2 & grp_fu_184_p2);

assign sel_tmp7_fu_598_p2 = (grp_fu_196_p2 | uart_to_coordinates_current_in_fu_580_p2);

assign sel_tmp9_fu_610_p2 = (tmp2_fu_604_p2 & grp_fu_184_p2);

assign sel_tmp_fu_616_p2 = (grp_fu_196_p2 & uart_to_coordinates_current_input_V_read);

assign sel_tmp_i_fu_424_p2 = (tmp_i1_fu_312_p2 ^ ap_const_lv1_1);

assign tmp1_fu_462_p2 = (grp_fu_190_p2 & tmp_i1_fu_312_p2);

assign tmp2_fu_604_p2 = (grp_fu_190_p2 & uart_to_coordinates_current_in_fu_580_p2);

assign tmp_10_fu_234_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_F? 1'b1: 1'b0);

assign tmp_11_fu_408_p1 = tmp_65_i_fu_374_p2;

assign tmp_12_fu_240_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_E? 1'b1: 1'b0);

assign tmp_13_fu_474_p2 = (sel_tmp6_i_fu_468_p2 | sel_tmp4_i_fu_456_p2);

assign tmp_14_fu_246_p2 = (tmp_12_fu_240_p2 | tmp_10_fu_234_p2);

assign tmp_15_fu_252_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_D? 1'b1: 1'b0);

assign tmp_16_fu_258_p2 = (tmp_15_fu_252_p2 | tmp_14_fu_246_p2);

assign tmp_17_fu_264_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_C? 1'b1: 1'b0);

assign tmp_18_fu_270_p2 = (tmp_17_fu_264_p2 | tmp_16_fu_258_p2);

assign tmp_19_fu_276_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_B? 1'b1: 1'b0);

assign tmp_1_fu_228_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_1? 1'b1: 1'b0);

assign tmp_20_fu_282_p2 = (tmp_19_fu_276_p2 | tmp_18_fu_270_p2);

assign tmp_21_fu_288_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_A? 1'b1: 1'b0);

assign tmp_22_fu_294_p2 = (tmp_21_fu_288_p2 | tmp_20_fu_282_p2);

assign tmp_23_fu_300_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_0? 1'b1: 1'b0);

assign tmp_24_fu_306_p2 = (tmp_23_fu_300_p2 | tmp_22_fu_294_p2);

assign tmp_25_fu_328_p3 = r_V_4_fu_322_p2[ap_const_lv32_4];

assign tmp_26_fu_390_p1 = tmp_61_i_fu_360_p2[7:0];

assign tmp_27_fu_412_p1 = tmp_68_i_fu_380_p2[7:0];

assign tmp_2_fu_693_p2 = (uart_to_coordinates_count_V_i == ap_const_lv16_37DC? 1'b1: 1'b0);

assign tmp_3_fu_568_p2 = (uart_to_coordinates_uart_state_V_i < ap_const_lv4_D? 1'b1: 1'b0);

assign tmp_56_i_cast_fu_340_p1 = uart_to_coordinates_previous_input_V_i;

assign tmp_56_i_fu_336_p1 = uart_to_coordinates_previous_input_V_i;

assign tmp_57_i_fu_344_p2 = (ap_const_lv5_2 - lhs_V_1_i_cast_fu_318_p1);

assign tmp_58_i_fu_350_p2 = tmp_56_i_cast_fu_340_p1 >> tmp_57_i_fu_344_p2;

assign tmp_5_fu_386_p1 = tmp_58_i_fu_350_p2;

assign tmp_60_i_fu_356_p1 = $signed(r_V_4_fu_322_p2);

assign tmp_61_i_fu_360_p2 = tmp_56_i_fu_336_p1 << tmp_60_i_fu_356_p1;

assign tmp_63_i_cast_fu_370_p1 = uart_to_coordinates_current_input_V_read;

assign tmp_63_i_fu_366_p1 = uart_to_coordinates_current_input_V_read;

assign tmp_65_i_fu_374_p2 = tmp_63_i_cast_fu_370_p1 >> tmp_57_i_fu_344_p2;

assign tmp_68_i_fu_380_p2 = tmp_63_i_fu_366_p1 << tmp_60_i_fu_356_p1;

assign tmp_70_i_fu_402_p2 = (ap_const_lv4_1 + uart_to_coordinates_uart_state_V_i);

assign tmp_9_fu_562_p2 = (uart_to_coordinates_uart_state_V_i > ap_const_lv4_9? 1'b1: 1'b0);

assign tmp_fu_222_p2 = (uart_to_coordinates_uart_state_V_i == ap_const_lv4_0? 1'b1: 1'b0);

assign tmp_i1_fu_312_p2 = (uart_to_coordinates_previous_input_V_i ^ uart_to_coordinates_current_input_V_read);

assign uart_to_coordinates_count_V_wr_1_fu_666_p3 = ((uart_to_coordinates_uart_state_2_fu_622_p2[0:0] === 1'b1) ? newSel6_fu_650_p3 : newSel7_fu_658_p3);

assign uart_to_coordinates_count_V_wr_fu_480_p3 = ((tmp_13_fu_474_p2[0:0] === 1'b1) ? ap_const_lv16_1 : sel_tmp2_i_fu_444_p2);

assign uart_to_coordinates_current_in_1_read_fu_86_p2 = uart_to_coordinates_current_input_V_read;

assign uart_to_coordinates_current_in_fu_580_p2 = (uart_to_coordinates_current_input_V_read ^ ap_const_lv1_1);

assign uart_to_coordinates_current_ou_fu_641_p3 = ((sel_tmp9_fu_610_p2[0:0] === 1'b1) ? uart_to_coordinates_next_out_byte_V_i : sel_tmp1_fu_633_p3);

assign uart_to_coordinates_next_out_b_1_fu_555_p2 = (uart_to_coordinates_next_out_byte_V_i | newSel5_fu_547_p3);

assign uart_to_coordinates_previous_i_1_fu_497_p3 = ((sel_tmp6_i_fu_468_p2[0:0] === 1'b1) ? uart_to_coordinates_current_input_V_read : sel_tmp13_i_fu_489_p3);

assign uart_to_coordinates_previous_i_2_fu_675_p3 = ((sel_tmp7_fu_598_p2[0:0] === 1'b1) ? sel_tmp_fu_616_p2 : uart_to_coordinates_previous_input_V_i);

assign uart_to_coordinates_uart_state_1_fu_522_p3 = ((tmp_13_fu_474_p2[0:0] === 1'b1) ? newSel_fu_506_p3 : newSel1_fu_514_p3);

assign uart_to_coordinates_uart_state_2_fu_622_p2 = (sel_tmp9_fu_610_p2 | sel_tmp_fu_616_p2);

assign uart_to_coordinates_uart_state_3_fu_629_p1 = uart_to_coordinates_uart_state_2_fu_622_p2;

assign uart_to_coordinates_uart_state_4_fu_684_p3 = ((sel_tmp7_fu_598_p2[0:0] === 1'b1) ? uart_to_coordinates_uart_state_3_fu_629_p1 : uart_to_coordinates_uart_state_V_i);


endmodule //master_ip_uart_to_byte

