// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module master_ip_mainFunction (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        uart_to_coordinates_count_V_i,
        uart_to_coordinates_count_V_o,
        uart_to_coordinates_count_V_o_ap_vld,
        uart_to_coordinates_previous_input_V_i,
        uart_to_coordinates_previous_input_V_o,
        uart_to_coordinates_previous_input_V_o_ap_vld,
        uart_to_coordinates_uart_state_V_i,
        uart_to_coordinates_uart_state_V_o,
        uart_to_coordinates_uart_state_V_o_ap_vld,
        uart_to_coordinates_next_out_byte_V_i,
        uart_to_coordinates_next_out_byte_V_o,
        uart_to_coordinates_next_out_byte_V_o_ap_vld,
        uart_to_coordinates_current_out_byte_V_read,
        uart_to_coordinates_gnss_state_V_read,
        uart_to_coordinates_ck_a_V_read,
        uart_to_coordinates_ck_b_V_read,
        uart_to_coordinates_tempCoordinates_0_i,
        uart_to_coordinates_tempCoordinates_0_o,
        uart_to_coordinates_tempCoordinates_0_o_ap_vld,
        uart_to_coordinates_tempCoordinates_1_i,
        uart_to_coordinates_tempCoordinates_1_o,
        uart_to_coordinates_tempCoordinates_1_o_ap_vld,
        uart_to_coordinates_tempCoordinates_2_i,
        uart_to_coordinates_tempCoordinates_2_o,
        uart_to_coordinates_tempCoordinates_2_o_ap_vld,
        input_V_read,
        p_read,
        p_read2,
        p_read5,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b1;
parameter    ap_ST_st2_fsm_1 = 3'b10;
parameter    ap_ST_st3_fsm_2 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv6_39 = 6'b111001;
parameter    ap_const_lv6_3C = 6'b111100;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv6_3F = 6'b111111;
parameter    ap_const_lv6_3E = 6'b111110;
parameter    ap_const_lv6_3D = 6'b111101;
parameter    ap_const_lv6_3B = 6'b111011;
parameter    ap_const_lv6_3A = 6'b111010;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] uart_to_coordinates_count_V_i;
output  [15:0] uart_to_coordinates_count_V_o;
output   uart_to_coordinates_count_V_o_ap_vld;
input  [0:0] uart_to_coordinates_previous_input_V_i;
output  [0:0] uart_to_coordinates_previous_input_V_o;
output   uart_to_coordinates_previous_input_V_o_ap_vld;
input  [3:0] uart_to_coordinates_uart_state_V_i;
output  [3:0] uart_to_coordinates_uart_state_V_o;
output   uart_to_coordinates_uart_state_V_o_ap_vld;
input  [7:0] uart_to_coordinates_next_out_byte_V_i;
output  [7:0] uart_to_coordinates_next_out_byte_V_o;
output   uart_to_coordinates_next_out_byte_V_o_ap_vld;
input  [7:0] uart_to_coordinates_current_out_byte_V_read;
input  [5:0] uart_to_coordinates_gnss_state_V_read;
input  [7:0] uart_to_coordinates_ck_a_V_read;
input  [7:0] uart_to_coordinates_ck_b_V_read;
input  [31:0] uart_to_coordinates_tempCoordinates_0_i;
output  [31:0] uart_to_coordinates_tempCoordinates_0_o;
output   uart_to_coordinates_tempCoordinates_0_o_ap_vld;
input  [31:0] uart_to_coordinates_tempCoordinates_1_i;
output  [31:0] uart_to_coordinates_tempCoordinates_1_o;
output   uart_to_coordinates_tempCoordinates_1_o_ap_vld;
input  [31:0] uart_to_coordinates_tempCoordinates_2_i;
output  [31:0] uart_to_coordinates_tempCoordinates_2_o;
output   uart_to_coordinates_tempCoordinates_2_o_ap_vld;
input  [0:0] input_V_read;
input  [31:0] p_read;
input  [31:0] p_read2;
input  [31:0] p_read5;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [5:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] uart_to_coordinates_count_V_o;
reg[0:0] uart_to_coordinates_previous_input_V_o;
reg[3:0] uart_to_coordinates_uart_state_V_o;
reg[7:0] uart_to_coordinates_next_out_byte_V_o;
reg[31:0] uart_to_coordinates_tempCoordinates_0_o;
reg[31:0] uart_to_coordinates_tempCoordinates_1_o;
reg[31:0] uart_to_coordinates_tempCoordinates_2_o;
reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;
reg[5:0] ap_return_3;
reg[31:0] ap_return_4;
reg[31:0] ap_return_5;
reg[31:0] ap_return_6;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm = 3'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_21;
wire   [0:0] tmp_fu_199_p1;
reg   [0:0] tmp_reg_455;
reg   [7:0] uart_to_coordinates_current_ou_reg_459;
wire   [7:0] uart_to_coordinates_ck_a_V_1_i_fu_328_p3;
reg   [7:0] uart_to_coordinates_ck_a_V_1_i_reg_466;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_89;
wire   [7:0] uart_to_coordinates_ck_b_V_1_i_fu_337_p3;
reg   [7:0] uart_to_coordinates_ck_b_V_1_i_reg_472;
wire    grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start;
wire    grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done;
wire    grp_master_ip_get_gps_info_from_ubx_fu_166_ap_idle;
wire    grp_master_ip_get_gps_info_from_ubx_fu_166_ap_ready;
wire   [7:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read;
wire   [5:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read;
wire   [7:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read;
wire   [7:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o;
wire    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o;
wire    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o;
wire    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5;
wire   [5:0] grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2;
wire   [31:0] grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3;
wire   [15:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i;
wire   [15:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o;
wire    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld;
wire   [0:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i;
wire   [0:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o;
wire    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld;
wire   [0:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read;
wire   [3:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i;
wire   [3:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o;
wire    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld;
wire   [7:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i;
wire   [7:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o;
wire    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld;
wire   [7:0] call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read;
wire   [0:0] call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0;
wire   [7:0] call_ret6_master_ip_uart_to_byte_fu_183_ap_return_1;
reg   [31:0] coordinates_phi_fu_115_p4;
reg   [31:0] coordinates_reg_112;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_148;
reg   [31:0] coordinates_1_phi_fu_124_p4;
reg   [31:0] coordinates_1_reg_121;
reg   [31:0] coordinates_2_phi_fu_133_p4;
reg   [31:0] coordinates_2_reg_130;
reg   [7:0] uart_to_coordinates_ck_a_V_phi_fu_142_p4;
reg   [7:0] uart_to_coordinates_ck_a_V_reg_139;
reg   [7:0] uart_to_coordinates_ck_b_V_phi_fu_151_p4;
reg   [7:0] uart_to_coordinates_ck_b_V_reg_148;
reg   [5:0] uart_to_coordinates_gnss_state_phi_fu_160_p4;
reg   [5:0] uart_to_coordinates_gnss_state_reg_157;
reg    grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg = 1'b0;
wire   [7:0] tmp_i_fu_207_p2;
wire   [0:0] tmp_86_i_fu_216_p2;
wire   [0:0] tmp_87_i_fu_221_p2;
wire   [0:0] or_cond4_i_fu_226_p2;
wire   [0:0] sel_tmp5_fu_271_p2;
wire   [0:0] sel_tmp6_fu_276_p2;
wire   [0:0] sel_tmp4_fu_266_p2;
wire   [0:0] sel_tmp3_fu_261_p2;
wire   [0:0] tmp7_fu_292_p2;
wire   [0:0] tmp6_fu_286_p2;
wire   [0:0] sel_tmp_fu_246_p2;
wire   [0:0] sel_tmp2_fu_256_p2;
wire   [0:0] sel_tmp1_fu_251_p2;
wire   [0:0] sel_tmp7_fu_281_p2;
wire   [0:0] tmp10_fu_310_p2;
wire   [0:0] tmp9_fu_304_p2;
wire   [0:0] tmp11_fu_316_p2;
wire   [0:0] tmp8_fu_298_p2;
wire   [0:0] sel_tmp8_fu_322_p2;
wire   [7:0] uart_to_coordinates_ck_a_V_rea_fu_232_p3;
wire   [7:0] uart_to_coordinates_ck_b_V_rea_fu_239_p3;
wire   [7:0] tmp_85_i_fu_211_p2;
reg   [7:0] ap_return_0_preg = 8'b00000000;
reg   [7:0] ap_return_1_preg = 8'b00000000;
reg   [7:0] ap_return_2_preg = 8'b00000000;
reg   [5:0] ap_return_3_preg = 6'b000000;
reg   [31:0] ap_return_4_preg = 32'b00000000000000000000000000000000;
reg   [31:0] ap_return_5_preg = 32'b00000000000000000000000000000000;
reg   [31:0] ap_return_6_preg = 32'b00000000000000000000000000000000;
reg   [2:0] ap_NS_fsm;


master_ip_get_gps_info_from_ubx grp_master_ip_get_gps_info_from_ubx_fu_166(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start ),
    .ap_done( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done ),
    .ap_idle( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_idle ),
    .ap_ready( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_ready ),
    .uart_to_coordinates_current_out_byte_V_read( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read ),
    .uart_to_coordinates_gnss_state_V_read( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read ),
    .uart_to_coordinates_ck_a_V_read( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read ),
    .uart_to_coordinates_ck_b_V_read( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read ),
    .uart_to_coordinates_tempCoordinates_0_i( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i ),
    .uart_to_coordinates_tempCoordinates_0_o( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o ),
    .uart_to_coordinates_tempCoordinates_0_o_ap_vld( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld ),
    .uart_to_coordinates_tempCoordinates_1_i( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i ),
    .uart_to_coordinates_tempCoordinates_1_o( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o ),
    .uart_to_coordinates_tempCoordinates_1_o_ap_vld( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld ),
    .uart_to_coordinates_tempCoordinates_2_i( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i ),
    .uart_to_coordinates_tempCoordinates_2_o( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o ),
    .uart_to_coordinates_tempCoordinates_2_o_ap_vld( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld ),
    .p_read1( grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1 ),
    .p_read4( grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4 ),
    .p_read5( grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5 ),
    .ap_return_0( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0 ),
    .ap_return_1( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1 ),
    .ap_return_2( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2 ),
    .ap_return_3( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3 )
);

master_ip_uart_to_byte call_ret6_master_ip_uart_to_byte_fu_183(
    .uart_to_coordinates_count_V_i( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i ),
    .uart_to_coordinates_count_V_o( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o ),
    .uart_to_coordinates_count_V_o_ap_vld( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld ),
    .uart_to_coordinates_previous_input_V_i( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i ),
    .uart_to_coordinates_previous_input_V_o( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o ),
    .uart_to_coordinates_previous_input_V_o_ap_vld( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld ),
    .uart_to_coordinates_current_input_V_read( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read ),
    .uart_to_coordinates_uart_state_V_i( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i ),
    .uart_to_coordinates_uart_state_V_o( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o ),
    .uart_to_coordinates_uart_state_V_o_ap_vld( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld ),
    .uart_to_coordinates_next_out_byte_V_i( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i ),
    .uart_to_coordinates_next_out_byte_V_o( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o ),
    .uart_to_coordinates_next_out_byte_V_o_ap_vld( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld ),
    .uart_to_coordinates_current_out_byte_V_read( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read ),
    .ap_return_0( call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0 ),
    .ap_return_1( call_ret6_master_ip_uart_to_byte_fu_183_ap_return_1 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_return_0_preg
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= ap_const_lv8_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
            ap_return_0_preg <= uart_to_coordinates_ck_a_V_phi_fu_142_p4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_return_1_preg
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= ap_const_lv8_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
            ap_return_1_preg <= uart_to_coordinates_ck_b_V_phi_fu_151_p4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_return_2_preg
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= ap_const_lv8_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
            ap_return_2_preg <= uart_to_coordinates_current_ou_reg_459;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_return_3_preg
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= ap_const_lv6_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
            ap_return_3_preg <= uart_to_coordinates_gnss_state_phi_fu_160_p4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_return_4_preg
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= ap_const_lv32_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
            ap_return_4_preg <= coordinates_phi_fu_115_p4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_return_5_preg
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= ap_const_lv32_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
            ap_return_5_preg <= coordinates_1_phi_fu_124_p4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_return_6_preg
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= ap_const_lv32_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
            ap_return_6_preg <= coordinates_2_phi_fu_133_p4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
            grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_ready)) begin
            grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        coordinates_1_reg_121 <= grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (tmp_fu_199_p1 == ap_const_lv1_0))) begin
        coordinates_1_reg_121 <= p_read2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        coordinates_2_reg_130 <= grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (tmp_fu_199_p1 == ap_const_lv1_0))) begin
        coordinates_2_reg_130 <= p_read5;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        coordinates_reg_112 <= grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (tmp_fu_199_p1 == ap_const_lv1_0))) begin
        coordinates_reg_112 <= p_read;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        uart_to_coordinates_ck_a_V_reg_139 <= uart_to_coordinates_ck_a_V_1_i_reg_466;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (tmp_fu_199_p1 == ap_const_lv1_0))) begin
        uart_to_coordinates_ck_a_V_reg_139 <= uart_to_coordinates_ck_a_V_read;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        uart_to_coordinates_ck_b_V_reg_148 <= uart_to_coordinates_ck_b_V_1_i_reg_472;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (tmp_fu_199_p1 == ap_const_lv1_0))) begin
        uart_to_coordinates_ck_b_V_reg_148 <= uart_to_coordinates_ck_b_V_read;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        uart_to_coordinates_gnss_state_reg_157 <= grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (tmp_fu_199_p1 == ap_const_lv1_0))) begin
        uart_to_coordinates_gnss_state_reg_157 <= uart_to_coordinates_gnss_state_V_read;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        tmp_reg_455 <= call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0;
        uart_to_coordinates_current_ou_reg_459 <= call_ret6_master_ip_uart_to_byte_fu_183_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        uart_to_coordinates_ck_a_V_1_i_reg_466 <= uart_to_coordinates_ck_a_V_1_i_fu_328_p3;
        uart_to_coordinates_ck_b_V_1_i_reg_472 <= uart_to_coordinates_ck_b_V_1_i_fu_337_p3;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or ap_sig_cseq_ST_st3_fsm_2) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done))))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or ap_sig_cseq_ST_st3_fsm_2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or ap_sig_cseq_ST_st3_fsm_2 or uart_to_coordinates_ck_a_V_phi_fu_142_p4 or ap_return_0_preg) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        ap_return_0 = uart_to_coordinates_ck_a_V_phi_fu_142_p4;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or ap_sig_cseq_ST_st3_fsm_2 or uart_to_coordinates_ck_b_V_phi_fu_151_p4 or ap_return_1_preg) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        ap_return_1 = uart_to_coordinates_ck_b_V_phi_fu_151_p4;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (tmp_reg_455 or uart_to_coordinates_current_ou_reg_459 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or ap_sig_cseq_ST_st3_fsm_2 or ap_return_2_preg) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        ap_return_2 = uart_to_coordinates_current_ou_reg_459;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or ap_sig_cseq_ST_st3_fsm_2 or uart_to_coordinates_gnss_state_phi_fu_160_p4 or ap_return_3_preg) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        ap_return_3 = uart_to_coordinates_gnss_state_phi_fu_160_p4;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or coordinates_phi_fu_115_p4 or ap_sig_cseq_ST_st3_fsm_2 or ap_return_4_preg) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        ap_return_4 = coordinates_phi_fu_115_p4;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or ap_sig_cseq_ST_st3_fsm_2 or coordinates_1_phi_fu_124_p4 or ap_return_5_preg) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        ap_return_5 = coordinates_1_phi_fu_124_p4;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done or ap_sig_cseq_ST_st3_fsm_2 or coordinates_2_phi_fu_133_p4 or ap_return_6_preg) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done)))) begin
        ap_return_6 = coordinates_2_phi_fu_133_p4;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (ap_sig_bdd_21) begin
    if (ap_sig_bdd_21) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_89) begin
    if (ap_sig_bdd_89) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_148) begin
    if (ap_sig_bdd_148) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2 or ap_sig_cseq_ST_st3_fsm_2 or coordinates_1_reg_121) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0))) begin
        coordinates_1_phi_fu_124_p4 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2;
    end else begin
        coordinates_1_phi_fu_124_p4 = coordinates_1_reg_121;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3 or ap_sig_cseq_ST_st3_fsm_2 or coordinates_2_reg_130) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0))) begin
        coordinates_2_phi_fu_133_p4 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3;
    end else begin
        coordinates_2_phi_fu_133_p4 = coordinates_2_reg_130;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1 or coordinates_reg_112 or ap_sig_cseq_ST_st3_fsm_2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0))) begin
        coordinates_phi_fu_115_p4 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1;
    end else begin
        coordinates_phi_fu_115_p4 = coordinates_reg_112;
    end
end

always @ (tmp_reg_455 or uart_to_coordinates_ck_a_V_1_i_reg_466 or ap_sig_cseq_ST_st3_fsm_2 or uart_to_coordinates_ck_a_V_reg_139) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0))) begin
        uart_to_coordinates_ck_a_V_phi_fu_142_p4 = uart_to_coordinates_ck_a_V_1_i_reg_466;
    end else begin
        uart_to_coordinates_ck_a_V_phi_fu_142_p4 = uart_to_coordinates_ck_a_V_reg_139;
    end
end

always @ (tmp_reg_455 or uart_to_coordinates_ck_b_V_1_i_reg_472 or ap_sig_cseq_ST_st3_fsm_2 or uart_to_coordinates_ck_b_V_reg_148) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0))) begin
        uart_to_coordinates_ck_b_V_phi_fu_151_p4 = uart_to_coordinates_ck_b_V_1_i_reg_472;
    end else begin
        uart_to_coordinates_ck_b_V_phi_fu_151_p4 = uart_to_coordinates_ck_b_V_reg_148;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or uart_to_coordinates_count_V_i or call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o or call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (ap_const_logic_1 == call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld))) begin
        uart_to_coordinates_count_V_o = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o;
    end else begin
        uart_to_coordinates_count_V_o = uart_to_coordinates_count_V_i;
    end
end

always @ (tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0 or ap_sig_cseq_ST_st3_fsm_2 or uart_to_coordinates_gnss_state_reg_157) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0))) begin
        uart_to_coordinates_gnss_state_phi_fu_160_p4 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0;
    end else begin
        uart_to_coordinates_gnss_state_phi_fu_160_p4 = uart_to_coordinates_gnss_state_reg_157;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or uart_to_coordinates_next_out_byte_V_i or call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o or call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (ap_const_logic_1 == call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld))) begin
        uart_to_coordinates_next_out_byte_V_o = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o;
    end else begin
        uart_to_coordinates_next_out_byte_V_o = uart_to_coordinates_next_out_byte_V_i;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or uart_to_coordinates_previous_input_V_i or call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o or call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (ap_const_logic_1 == call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld))) begin
        uart_to_coordinates_previous_input_V_o = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o;
    end else begin
        uart_to_coordinates_previous_input_V_o = uart_to_coordinates_previous_input_V_i;
    end
end

always @ (uart_to_coordinates_tempCoordinates_0_i or tmp_reg_455 or ap_sig_cseq_ST_st2_fsm_1 or grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o or grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld or ap_sig_cseq_ST_st3_fsm_2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_logic_1 == grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_1 == grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld)))) begin
        uart_to_coordinates_tempCoordinates_0_o = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o;
    end else begin
        uart_to_coordinates_tempCoordinates_0_o = uart_to_coordinates_tempCoordinates_0_i;
    end
end

always @ (uart_to_coordinates_tempCoordinates_1_i or tmp_reg_455 or ap_sig_cseq_ST_st2_fsm_1 or grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o or grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld or ap_sig_cseq_ST_st3_fsm_2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_logic_1 == grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_1 == grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld)))) begin
        uart_to_coordinates_tempCoordinates_1_o = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o;
    end else begin
        uart_to_coordinates_tempCoordinates_1_o = uart_to_coordinates_tempCoordinates_1_i;
    end
end

always @ (uart_to_coordinates_tempCoordinates_2_i or tmp_reg_455 or ap_sig_cseq_ST_st2_fsm_1 or grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o or grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld or ap_sig_cseq_ST_st3_fsm_2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (ap_const_logic_1 == grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_1 == grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld)))) begin
        uart_to_coordinates_tempCoordinates_2_o = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o;
    end else begin
        uart_to_coordinates_tempCoordinates_2_o = uart_to_coordinates_tempCoordinates_2_i;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or uart_to_coordinates_uart_state_V_i or call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o or call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & (ap_const_logic_1 == call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld))) begin
        uart_to_coordinates_uart_state_V_o = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o;
    end else begin
        uart_to_coordinates_uart_state_V_o = uart_to_coordinates_uart_state_V_i;
    end
end
always @ (ap_start or ap_CS_fsm or tmp_fu_199_p1 or tmp_reg_455 or grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if ((~(ap_start == ap_const_logic_0) & (tmp_fu_199_p1 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else if ((~(ap_start == ap_const_logic_0) & ~(tmp_fu_199_p1 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(~(tmp_reg_455 == ap_const_lv1_0) & (ap_const_logic_0 == grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_148 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_21 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_89 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i = uart_to_coordinates_count_V_i;

assign call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read = input_V_read;

assign call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read = uart_to_coordinates_current_out_byte_V_read;

assign call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i = uart_to_coordinates_next_out_byte_V_i;

assign call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i = uart_to_coordinates_previous_input_V_i;

assign call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i = uart_to_coordinates_uart_state_V_i;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1 = p_read;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4 = p_read2;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5 = p_read5;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read = uart_to_coordinates_ck_a_V_1_i_reg_466;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read = uart_to_coordinates_ck_b_V_1_i_reg_472;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read = uart_to_coordinates_current_ou_reg_459;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read = uart_to_coordinates_gnss_state_V_read;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i = uart_to_coordinates_tempCoordinates_0_i;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i = uart_to_coordinates_tempCoordinates_1_i;

assign grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i = uart_to_coordinates_tempCoordinates_2_i;

assign or_cond4_i_fu_226_p2 = (tmp_86_i_fu_216_p2 & tmp_87_i_fu_221_p2);

assign sel_tmp1_fu_251_p2 = (uart_to_coordinates_gnss_state_V_read == ap_const_lv6_3E? 1'b1: 1'b0);

assign sel_tmp2_fu_256_p2 = (uart_to_coordinates_gnss_state_V_read == ap_const_lv6_3D? 1'b1: 1'b0);

assign sel_tmp3_fu_261_p2 = (uart_to_coordinates_gnss_state_V_read == ap_const_lv6_3C? 1'b1: 1'b0);

assign sel_tmp4_fu_266_p2 = (uart_to_coordinates_gnss_state_V_read == ap_const_lv6_3B? 1'b1: 1'b0);

assign sel_tmp5_fu_271_p2 = (uart_to_coordinates_gnss_state_V_read == ap_const_lv6_3A? 1'b1: 1'b0);

assign sel_tmp6_fu_276_p2 = (uart_to_coordinates_gnss_state_V_read == ap_const_lv6_1? 1'b1: 1'b0);

assign sel_tmp7_fu_281_p2 = (uart_to_coordinates_gnss_state_V_read == ap_const_lv6_0? 1'b1: 1'b0);

assign sel_tmp8_fu_322_p2 = (tmp11_fu_316_p2 | tmp8_fu_298_p2);

assign sel_tmp_fu_246_p2 = (uart_to_coordinates_gnss_state_V_read == ap_const_lv6_3F? 1'b1: 1'b0);

assign tmp10_fu_310_p2 = (sel_tmp1_fu_251_p2 | sel_tmp7_fu_281_p2);

assign tmp11_fu_316_p2 = (tmp10_fu_310_p2 | tmp9_fu_304_p2);

assign tmp6_fu_286_p2 = (sel_tmp5_fu_271_p2 | sel_tmp6_fu_276_p2);

assign tmp7_fu_292_p2 = (sel_tmp4_fu_266_p2 | sel_tmp3_fu_261_p2);

assign tmp8_fu_298_p2 = (tmp7_fu_292_p2 | tmp6_fu_286_p2);

assign tmp9_fu_304_p2 = (sel_tmp_fu_246_p2 | sel_tmp2_fu_256_p2);

assign tmp_85_i_fu_211_p2 = (tmp_i_fu_207_p2 + uart_to_coordinates_ck_b_V_read);

assign tmp_86_i_fu_216_p2 = (uart_to_coordinates_gnss_state_V_read > ap_const_lv6_39? 1'b1: 1'b0);

assign tmp_87_i_fu_221_p2 = (uart_to_coordinates_gnss_state_V_read < ap_const_lv6_3C? 1'b1: 1'b0);

assign tmp_fu_199_p1 = call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0;

assign tmp_i_fu_207_p2 = (uart_to_coordinates_current_ou_reg_459 + uart_to_coordinates_ck_a_V_read);

assign uart_to_coordinates_ck_a_V_1_i_fu_328_p3 = ((sel_tmp8_fu_322_p2[0:0] === 1'b1) ? uart_to_coordinates_ck_a_V_rea_fu_232_p3 : tmp_i_fu_207_p2);

assign uart_to_coordinates_ck_a_V_rea_fu_232_p3 = ((or_cond4_i_fu_226_p2[0:0] === 1'b1) ? uart_to_coordinates_ck_a_V_read : ap_const_lv8_0);

assign uart_to_coordinates_ck_b_V_1_i_fu_337_p3 = ((sel_tmp8_fu_322_p2[0:0] === 1'b1) ? uart_to_coordinates_ck_b_V_rea_fu_239_p3 : tmp_85_i_fu_211_p2);

assign uart_to_coordinates_ck_b_V_rea_fu_239_p3 = ((or_cond4_i_fu_226_p2[0:0] === 1'b1) ? uart_to_coordinates_ck_b_V_read : ap_const_lv8_0);

assign uart_to_coordinates_count_V_o_ap_vld = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld;

assign uart_to_coordinates_next_out_byte_V_o_ap_vld = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld;

assign uart_to_coordinates_previous_input_V_o_ap_vld = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld;

assign uart_to_coordinates_tempCoordinates_0_o_ap_vld = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld;

assign uart_to_coordinates_tempCoordinates_1_o_ap_vld = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld;

assign uart_to_coordinates_tempCoordinates_2_o_ap_vld = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld;

assign uart_to_coordinates_uart_state_V_o_ap_vld = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld;


endmodule //master_ip_mainFunction

