lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/uart_to_coordinates.cpp" location "master_ip" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'master_ip' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/uart_to_coordinates.cpp" location "master_ip" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'master_ip' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/uart_to_coordinates.cpp" location "master_ip" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'master_ip' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/uart_to_coordinates.cpp" location "master_ip" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'master_ip' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/uart_to_coordinates.cpp" location "master_ip" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'master_ip' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/master_ip.cpp" location "master_ip" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/master_ip.cpp" location "master_ip" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/master_ip.cpp" location "master_ip" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/master_ip.cpp" location "master_ip" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INTERFACE" source "C:/Users/mxfr/Vivado/master_ip/master_ip.cpp" location "master_ip" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
