// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "master_ip.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic master_ip::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic master_ip::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> master_ip::ap_ST_pp0_stg0_fsm_0 = "1";
const sc_lv<2> master_ip::ap_ST_pp0_stg1_fsm_1 = "10";
const sc_lv<32> master_ip::ap_const_lv32_0 = "00000000000000000000000000000000";
const int master_ip::C_S_AXI_DATA_WIDTH = "100000";
const bool master_ip::ap_true = true;
const sc_lv<32> master_ip::ap_const_lv32_1 = "1";
const sc_lv<1> master_ip::ap_const_lv1_1 = "1";
const sc_lv<32> master_ip::ap_const_lv32_3F = "111111";
const sc_lv<32> master_ip::ap_const_lv32_34 = "110100";
const sc_lv<32> master_ip::ap_const_lv32_3E = "111110";
const sc_lv<12> master_ip::ap_const_lv12_C01 = "110000000001";
const sc_lv<32> master_ip::ap_const_lv32_B = "1011";
const sc_lv<11> master_ip::ap_const_lv11_3FF = "1111111111";
const sc_lv<32> master_ip::ap_const_lv32_53 = "1010011";
const sc_lv<32> master_ip::ap_const_lv32_3E8 = "1111101000";
const sc_lv<64> master_ip::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";

master_ip::master_ip(sc_module_name name) : sc_module(name), mVcdFile(0) {
    master_ip_AXILiteS_s_axi_U = new master_ip_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("master_ip_AXILiteS_s_axi_U");
    master_ip_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    master_ip_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    master_ip_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    master_ip_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    master_ip_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    master_ip_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    master_ip_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    master_ip_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    master_ip_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    master_ip_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    master_ip_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    master_ip_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    master_ip_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    master_ip_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    master_ip_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    master_ip_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    master_ip_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    master_ip_AXILiteS_s_axi_U->ACLK(ap_clk);
    master_ip_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    master_ip_AXILiteS_s_axi_U->ACLK_EN(master_ip_AXILiteS_s_axi_U_ap_dummy_ce);
    master_ip_AXILiteS_s_axi_U->axi_byte_V(axi_byte_V);
    grp_master_ip_mainFunction_fu_143 = new master_ip_mainFunction("grp_master_ip_mainFunction_fu_143");
    grp_master_ip_mainFunction_fu_143->ap_clk(ap_clk);
    grp_master_ip_mainFunction_fu_143->ap_rst(ap_rst_n_inv);
    grp_master_ip_mainFunction_fu_143->ap_start(grp_master_ip_mainFunction_fu_143_ap_start);
    grp_master_ip_mainFunction_fu_143->ap_done(grp_master_ip_mainFunction_fu_143_ap_done);
    grp_master_ip_mainFunction_fu_143->ap_idle(grp_master_ip_mainFunction_fu_143_ap_idle);
    grp_master_ip_mainFunction_fu_143->ap_ready(grp_master_ip_mainFunction_fu_143_ap_ready);
    grp_master_ip_mainFunction_fu_143->ap_ce(grp_master_ip_mainFunction_fu_143_ap_ce);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_count_V_i(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_count_V_o(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_count_V_o_ap_vld(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o_ap_vld);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_previous_input_V_i(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_previous_input_V_o(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_previous_input_V_o_ap_vld(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o_ap_vld);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_uart_state_V_i(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_uart_state_V_o(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_uart_state_V_o_ap_vld(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o_ap_vld);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_next_out_byte_V_i(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_next_out_byte_V_o(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_next_out_byte_V_o_ap_vld(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o_ap_vld);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_current_out_byte_V_read(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_gnss_state_V_read(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_ck_a_V_read(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_ck_b_V_read(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_0_i(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_0_o(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_0_o_ap_vld(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o_ap_vld);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_1_i(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_1_o(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_1_o_ap_vld(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o_ap_vld);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_2_i(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_2_o(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o);
    grp_master_ip_mainFunction_fu_143->uart_to_coordinates_tempCoordinates_2_o_ap_vld(grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o_ap_vld);
    grp_master_ip_mainFunction_fu_143->input_V_read(grp_master_ip_mainFunction_fu_143_input_V_read);
    grp_master_ip_mainFunction_fu_143->p_read(grp_master_ip_mainFunction_fu_143_p_read);
    grp_master_ip_mainFunction_fu_143->p_read2(grp_master_ip_mainFunction_fu_143_p_read2);
    grp_master_ip_mainFunction_fu_143->p_read5(grp_master_ip_mainFunction_fu_143_p_read5);
    grp_master_ip_mainFunction_fu_143->ap_return_0(grp_master_ip_mainFunction_fu_143_ap_return_0);
    grp_master_ip_mainFunction_fu_143->ap_return_1(grp_master_ip_mainFunction_fu_143_ap_return_1);
    grp_master_ip_mainFunction_fu_143->ap_return_2(grp_master_ip_mainFunction_fu_143_ap_return_2);
    grp_master_ip_mainFunction_fu_143->ap_return_3(grp_master_ip_mainFunction_fu_143_ap_return_3);
    grp_master_ip_mainFunction_fu_143->ap_return_4(grp_master_ip_mainFunction_fu_143_ap_return_4);
    grp_master_ip_mainFunction_fu_143->ap_return_5(grp_master_ip_mainFunction_fu_143_ap_return_5);
    grp_master_ip_mainFunction_fu_143->ap_return_6(grp_master_ip_mainFunction_fu_143_ap_return_6);
    master_ip_dadd_64ns_64ns_64_4_full_dsp_U31 = new master_ip_dadd_64ns_64ns_64_4_full_dsp<1,4,64,64,64>("master_ip_dadd_64ns_64ns_64_4_full_dsp_U31");
    master_ip_dadd_64ns_64ns_64_4_full_dsp_U31->clk(ap_clk);
    master_ip_dadd_64ns_64ns_64_4_full_dsp_U31->reset(ap_rst_n_inv);
    master_ip_dadd_64ns_64ns_64_4_full_dsp_U31->din0(grp_fu_178_p0);
    master_ip_dadd_64ns_64ns_64_4_full_dsp_U31->din1(grp_fu_178_p1);
    master_ip_dadd_64ns_64ns_64_4_full_dsp_U31->ce(grp_fu_178_ce);
    master_ip_dadd_64ns_64ns_64_4_full_dsp_U31->dout(grp_fu_178_p2);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U32 = new master_ip_dmul_64ns_64ns_64_4_max_dsp<1,4,64,64,64>("master_ip_dmul_64ns_64ns_64_4_max_dsp_U32");
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U32->clk(ap_clk);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U32->reset(ap_rst_n_inv);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U32->din0(grp_fu_182_p0);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U32->din1(grp_fu_182_p1);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U32->ce(grp_fu_182_ce);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U32->dout(grp_fu_182_p2);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U33 = new master_ip_dmul_64ns_64ns_64_4_max_dsp<1,4,64,64,64>("master_ip_dmul_64ns_64ns_64_4_max_dsp_U33");
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U33->clk(ap_clk);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U33->reset(ap_rst_n_inv);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U33->din0(tmp_97_i_reg_577);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U33->din1(tmp_97_i_reg_577);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U33->ce(grp_fu_186_ce);
    master_ip_dmul_64ns_64ns_64_4_max_dsp_U33->dout(grp_fu_186_p2);
    master_ip_sitodp_32ns_64_3_U34 = new master_ip_sitodp_32ns_64_3<1,3,32,64>("master_ip_sitodp_32ns_64_3_U34");
    master_ip_sitodp_32ns_64_3_U34->clk(ap_clk);
    master_ip_sitodp_32ns_64_3_U34->reset(ap_rst_n_inv);
    master_ip_sitodp_32ns_64_3_U34->din0(grp_fu_190_p0);
    master_ip_sitodp_32ns_64_3_U34->ce(grp_fu_190_ce);
    master_ip_sitodp_32ns_64_3_U34->dout(grp_fu_190_p1);
    master_ip_sitodp_32ns_64_3_U35 = new master_ip_sitodp_32ns_64_3<1,3,32,64>("master_ip_sitodp_32ns_64_3_U35");
    master_ip_sitodp_32ns_64_3_U35->clk(ap_clk);
    master_ip_sitodp_32ns_64_3_U35->reset(ap_rst_n_inv);
    master_ip_sitodp_32ns_64_3_U35->din0(tmp_96_i_reg_561);
    master_ip_sitodp_32ns_64_3_U35->ce(grp_fu_193_ce);
    master_ip_sitodp_32ns_64_3_U35->dout(grp_fu_193_p1);
    master_ip_dsqrt_64ns_64ns_64_17_U36 = new master_ip_dsqrt_64ns_64ns_64_17<1,17,64,64,64>("master_ip_dsqrt_64ns_64ns_64_17_U36");
    master_ip_dsqrt_64ns_64ns_64_17_U36->clk(ap_clk);
    master_ip_dsqrt_64ns_64ns_64_17_U36->reset(ap_rst_n_inv);
    master_ip_dsqrt_64ns_64ns_64_17_U36->din0(ap_const_lv64_0);
    master_ip_dsqrt_64ns_64ns_64_17_U36->din1(tmp_103_i_reg_609);
    master_ip_dsqrt_64ns_64ns_64_17_U36->ce(grp_fu_196_ce);
    master_ip_dsqrt_64ns_64ns_64_17_U36->dout(grp_fu_196_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_alert_V);
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it18 );
    sensitive << ( p_Val2_5_fu_527_p3 );

    SC_METHOD(thread_ap_reg_ppiten_pp0_it0);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_bdd_145);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_93);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_0);
    sensitive << ( ap_sig_bdd_145 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg1_fsm_1);
    sensitive << ( ap_sig_bdd_93 );

    SC_METHOD(thread_ap_sig_pprstidle_pp0);

    SC_METHOD(thread_ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_fu_178_ce);

    SC_METHOD(thread_grp_fu_178_p0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( tmp_95_i_reg_589 );
    sensitive << ( tmp_99_i_reg_604 );

    SC_METHOD(thread_grp_fu_178_p1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );
    sensitive << ( ap_reg_ppiten_pp0_it7 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( tmp_98_i_reg_594 );
    sensitive << ( ap_reg_ppstg_tmp_102_i_reg_599_pp0_it7 );

    SC_METHOD(thread_grp_fu_182_ce);

    SC_METHOD(thread_grp_fu_182_p0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( tmp_i_12_reg_571 );
    sensitive << ( tmp_101_i_reg_583 );

    SC_METHOD(thread_grp_fu_182_p1);
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( tmp_i_12_reg_571 );
    sensitive << ( tmp_101_i_reg_583 );

    SC_METHOD(thread_grp_fu_186_ce);

    SC_METHOD(thread_grp_fu_190_ce);

    SC_METHOD(thread_grp_fu_190_p0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_i_reg_556 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );
    sensitive << ( tmp_100_i_reg_566 );

    SC_METHOD(thread_grp_fu_193_ce);

    SC_METHOD(thread_grp_fu_196_ce);

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_ap_ce);

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_ap_start);
    sensitive << ( grp_master_ip_mainFunction_fu_143_ap_start_ap_start_reg );
    sensitive << ( ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_input_V_read);
    sensitive << ( uart1_V );
    sensitive << ( uart2_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_p_read);
    sensitive << ( coordinates1_0 );
    sensitive << ( coordinates2_0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_p_read2);
    sensitive << ( coordinates1_1 );
    sensitive << ( coordinates2_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_p_read5);
    sensitive << ( coordinates1_2 );
    sensitive << ( coordinates2_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read);
    sensitive << ( signal1_ck_a_V );
    sensitive << ( signal2_ck_a_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read);
    sensitive << ( signal1_ck_b_V );
    sensitive << ( signal2_ck_b_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i);
    sensitive << ( signal1_count_V );
    sensitive << ( signal2_count_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read);
    sensitive << ( signal1_current_out_byte_V );
    sensitive << ( signal2_current_out_byte_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read);
    sensitive << ( signal1_gnss_state_V );
    sensitive << ( signal2_gnss_state_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i);
    sensitive << ( signal1_next_out_byte_V );
    sensitive << ( signal2_next_out_byte_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i);
    sensitive << ( signal1_previous_input_V );
    sensitive << ( signal2_previous_input_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i);
    sensitive << ( signal1_tempCoordinates_0 );
    sensitive << ( signal2_tempCoordinates_0 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i);
    sensitive << ( signal1_tempCoordinates_1 );
    sensitive << ( signal2_tempCoordinates_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i);
    sensitive << ( signal1_tempCoordinates_2 );
    sensitive << ( signal2_tempCoordinates_2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i);
    sensitive << ( signal1_uart_state_V );
    sensitive << ( signal2_uart_state_V );
    sensitive << ( ap_sig_cseq_ST_pp0_stg1_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_0 );

    SC_METHOD(thread_isNeg_fu_441_p3);
    sensitive << ( sh_assign_fu_435_p2 );

    SC_METHOD(thread_loc_V_1_fu_419_p1);
    sensitive << ( p_Val2_s_fu_398_p1 );

    SC_METHOD(thread_loc_V_fu_409_p4);
    sensitive << ( p_Val2_s_fu_398_p1 );

    SC_METHOD(thread_master_ip_AXILiteS_s_axi_U_ap_dummy_ce);

    SC_METHOD(thread_p_Result_1_fu_423_p3);
    sensitive << ( loc_V_1_fu_419_p1 );

    SC_METHOD(thread_p_Val2_3_fu_514_p3);
    sensitive << ( isNeg_reg_629 );
    sensitive << ( tmp_3_fu_501_p1 );
    sensitive << ( tmp_4_fu_504_p4 );

    SC_METHOD(thread_p_Val2_5_fu_527_p3);
    sensitive << ( p_Result_s_reg_619 );
    sensitive << ( p_Val2_3_fu_514_p3 );
    sensitive << ( p_Val2_7_i_i_i_fu_521_p2 );

    SC_METHOD(thread_p_Val2_7_i_i_i_fu_521_p2);
    sensitive << ( p_Val2_3_fu_514_p3 );

    SC_METHOD(thread_p_Val2_s_fu_398_p1);
    sensitive << ( x_assign_reg_614 );

    SC_METHOD(thread_sh_assign_1_cast_fu_467_p1);
    sensitive << ( sh_assign_1_fu_459_p3 );

    SC_METHOD(thread_sh_assign_1_fu_459_p3);
    sensitive << ( isNeg_fu_441_p3 );
    sensitive << ( sh_assign_fu_435_p2 );
    sensitive << ( tmp_i_i_i_cast_fu_455_p1 );

    SC_METHOD(thread_sh_assign_fu_435_p2);
    sensitive << ( tmp_i_i_i_i_cast1_fu_431_p1 );

    SC_METHOD(thread_tmp_100_i_fu_393_p2);
    sensitive << ( newret9_reg_551 );
    sensitive << ( grp_master_ip_mainFunction_fu_143_ap_return_6 );

    SC_METHOD(thread_tmp_3_fu_501_p1);
    sensitive << ( tmp_reg_639 );

    SC_METHOD(thread_tmp_4_fu_504_p4);
    sensitive << ( tmp_91_i_i_i_fu_495_p2 );

    SC_METHOD(thread_tmp_88_i_i_i_cast_fu_471_p1);
    sensitive << ( sh_assign_1_cast_fu_467_p1 );

    SC_METHOD(thread_tmp_88_i_i_i_fu_492_p1);
    sensitive << ( sh_assign_1_cast_reg_634 );

    SC_METHOD(thread_tmp_89_i_i_i_fu_475_p2);
    sensitive << ( p_Result_1_fu_423_p3 );
    sensitive << ( tmp_88_i_i_i_cast_fu_471_p1 );

    SC_METHOD(thread_tmp_91_i_i_i_fu_495_p2);
    sensitive << ( tmp_i_i_i_fu_489_p1 );
    sensitive << ( tmp_88_i_i_i_fu_492_p1 );

    SC_METHOD(thread_tmp_96_i_fu_388_p2);
    sensitive << ( newret8_reg_546 );
    sensitive << ( grp_master_ip_mainFunction_fu_143_ap_return_5 );

    SC_METHOD(thread_tmp_i_fu_383_p2);
    sensitive << ( newret7_reg_541 );
    sensitive << ( grp_master_ip_mainFunction_fu_143_ap_return_4 );

    SC_METHOD(thread_tmp_i_i_i_13_fu_449_p2);
    sensitive << ( loc_V_fu_409_p4 );

    SC_METHOD(thread_tmp_i_i_i_cast_fu_455_p1);
    sensitive << ( tmp_i_i_i_13_fu_449_p2 );

    SC_METHOD(thread_tmp_i_i_i_fu_489_p1);
    sensitive << ( p_Result_1_reg_624 );

    SC_METHOD(thread_tmp_i_i_i_i_cast1_fu_431_p1);
    sensitive << ( loc_V_fu_409_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_pprstidle_pp0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    signal1_ck_a_V = "00000000";
    signal1_ck_b_V = "00000000";
    signal1_current_out_byte_V = "00000000";
    signal1_gnss_state_V = "000000";
    coordinates1_0 = "00000000000000000000000000000000";
    coordinates1_1 = "00000000000000000000000000000000";
    coordinates1_2 = "00000000000000000000000000000000";
    signal1_count_V = "0000000000000000";
    signal1_previous_input_V = "0";
    signal1_uart_state_V = "0000";
    signal1_next_out_byte_V = "00000000";
    signal1_tempCoordinates_0 = "00000000000000000000000000000010";
    signal1_tempCoordinates_1 = "00000000000000000000000000000000";
    signal1_tempCoordinates_2 = "00000000000000000000000000000000";
    signal2_ck_a_V = "00000000";
    signal2_ck_b_V = "00000000";
    signal2_current_out_byte_V = "00000000";
    signal2_gnss_state_V = "000000";
    coordinates2_0 = "00000000000000000000000000000000";
    coordinates2_1 = "00000000000000000000000000000000";
    coordinates2_2 = "00000000000000000000000000000000";
    signal2_count_V = "0000000000000000";
    signal2_previous_input_V = "0";
    signal2_uart_state_V = "0000";
    signal2_next_out_byte_V = "00000000";
    signal2_tempCoordinates_0 = "00000000000000000000000000000010";
    signal2_tempCoordinates_1 = "00000000000000000000000000000000";
    signal2_tempCoordinates_2 = "00000000000000000000000000000000";
    ap_CS_fsm = "01";
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it9 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it10 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it11 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it12 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it13 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it14 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it15 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it16 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it17 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it18 = SC_LOGIC_0;
    grp_master_ip_mainFunction_fu_143_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "master_ip_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, uart1_V, "(port)uart1_V");
    sc_trace(mVcdFile, uart2_V, "(port)uart2_V");
    sc_trace(mVcdFile, alert_V, "(port)alert_V");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, axi_byte_V, "axi_byte_V");
    sc_trace(mVcdFile, signal1_ck_a_V, "signal1_ck_a_V");
    sc_trace(mVcdFile, signal1_ck_b_V, "signal1_ck_b_V");
    sc_trace(mVcdFile, signal1_current_out_byte_V, "signal1_current_out_byte_V");
    sc_trace(mVcdFile, signal1_gnss_state_V, "signal1_gnss_state_V");
    sc_trace(mVcdFile, coordinates1_0, "coordinates1_0");
    sc_trace(mVcdFile, coordinates1_1, "coordinates1_1");
    sc_trace(mVcdFile, coordinates1_2, "coordinates1_2");
    sc_trace(mVcdFile, signal1_count_V, "signal1_count_V");
    sc_trace(mVcdFile, signal1_previous_input_V, "signal1_previous_input_V");
    sc_trace(mVcdFile, signal1_uart_state_V, "signal1_uart_state_V");
    sc_trace(mVcdFile, signal1_next_out_byte_V, "signal1_next_out_byte_V");
    sc_trace(mVcdFile, signal1_tempCoordinates_0, "signal1_tempCoordinates_0");
    sc_trace(mVcdFile, signal1_tempCoordinates_1, "signal1_tempCoordinates_1");
    sc_trace(mVcdFile, signal1_tempCoordinates_2, "signal1_tempCoordinates_2");
    sc_trace(mVcdFile, signal2_ck_a_V, "signal2_ck_a_V");
    sc_trace(mVcdFile, signal2_ck_b_V, "signal2_ck_b_V");
    sc_trace(mVcdFile, signal2_current_out_byte_V, "signal2_current_out_byte_V");
    sc_trace(mVcdFile, signal2_gnss_state_V, "signal2_gnss_state_V");
    sc_trace(mVcdFile, coordinates2_0, "coordinates2_0");
    sc_trace(mVcdFile, coordinates2_1, "coordinates2_1");
    sc_trace(mVcdFile, coordinates2_2, "coordinates2_2");
    sc_trace(mVcdFile, signal2_count_V, "signal2_count_V");
    sc_trace(mVcdFile, signal2_previous_input_V, "signal2_previous_input_V");
    sc_trace(mVcdFile, signal2_uart_state_V, "signal2_uart_state_V");
    sc_trace(mVcdFile, signal2_next_out_byte_V, "signal2_next_out_byte_V");
    sc_trace(mVcdFile, signal2_tempCoordinates_0, "signal2_tempCoordinates_0");
    sc_trace(mVcdFile, signal2_tempCoordinates_1, "signal2_tempCoordinates_1");
    sc_trace(mVcdFile, signal2_tempCoordinates_2, "signal2_tempCoordinates_2");
    sc_trace(mVcdFile, master_ip_AXILiteS_s_axi_U_ap_dummy_ce, "master_ip_AXILiteS_s_axi_U_ap_dummy_ce");
    sc_trace(mVcdFile, newret7_reg_541, "newret7_reg_541");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg1_fsm_1, "ap_sig_cseq_ST_pp0_stg1_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_93, "ap_sig_bdd_93");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it9, "ap_reg_ppiten_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it10, "ap_reg_ppiten_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it11, "ap_reg_ppiten_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it12, "ap_reg_ppiten_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it13, "ap_reg_ppiten_pp0_it13");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it14, "ap_reg_ppiten_pp0_it14");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it15, "ap_reg_ppiten_pp0_it15");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it16, "ap_reg_ppiten_pp0_it16");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it17, "ap_reg_ppiten_pp0_it17");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it18, "ap_reg_ppiten_pp0_it18");
    sc_trace(mVcdFile, newret8_reg_546, "newret8_reg_546");
    sc_trace(mVcdFile, newret9_reg_551, "newret9_reg_551");
    sc_trace(mVcdFile, tmp_i_fu_383_p2, "tmp_i_fu_383_p2");
    sc_trace(mVcdFile, tmp_i_reg_556, "tmp_i_reg_556");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_0, "ap_sig_cseq_ST_pp0_stg0_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_145, "ap_sig_bdd_145");
    sc_trace(mVcdFile, tmp_96_i_fu_388_p2, "tmp_96_i_fu_388_p2");
    sc_trace(mVcdFile, tmp_96_i_reg_561, "tmp_96_i_reg_561");
    sc_trace(mVcdFile, tmp_100_i_fu_393_p2, "tmp_100_i_fu_393_p2");
    sc_trace(mVcdFile, tmp_100_i_reg_566, "tmp_100_i_reg_566");
    sc_trace(mVcdFile, grp_fu_190_p1, "grp_fu_190_p1");
    sc_trace(mVcdFile, tmp_i_12_reg_571, "tmp_i_12_reg_571");
    sc_trace(mVcdFile, grp_fu_193_p1, "grp_fu_193_p1");
    sc_trace(mVcdFile, tmp_97_i_reg_577, "tmp_97_i_reg_577");
    sc_trace(mVcdFile, tmp_101_i_reg_583, "tmp_101_i_reg_583");
    sc_trace(mVcdFile, grp_fu_182_p2, "grp_fu_182_p2");
    sc_trace(mVcdFile, tmp_95_i_reg_589, "tmp_95_i_reg_589");
    sc_trace(mVcdFile, grp_fu_186_p2, "grp_fu_186_p2");
    sc_trace(mVcdFile, tmp_98_i_reg_594, "tmp_98_i_reg_594");
    sc_trace(mVcdFile, tmp_102_i_reg_599, "tmp_102_i_reg_599");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_102_i_reg_599_pp0_it6, "ap_reg_ppstg_tmp_102_i_reg_599_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_102_i_reg_599_pp0_it7, "ap_reg_ppstg_tmp_102_i_reg_599_pp0_it7");
    sc_trace(mVcdFile, grp_fu_178_p2, "grp_fu_178_p2");
    sc_trace(mVcdFile, tmp_99_i_reg_604, "tmp_99_i_reg_604");
    sc_trace(mVcdFile, tmp_103_i_reg_609, "tmp_103_i_reg_609");
    sc_trace(mVcdFile, grp_fu_196_p2, "grp_fu_196_p2");
    sc_trace(mVcdFile, x_assign_reg_614, "x_assign_reg_614");
    sc_trace(mVcdFile, p_Result_s_reg_619, "p_Result_s_reg_619");
    sc_trace(mVcdFile, p_Result_1_fu_423_p3, "p_Result_1_fu_423_p3");
    sc_trace(mVcdFile, p_Result_1_reg_624, "p_Result_1_reg_624");
    sc_trace(mVcdFile, isNeg_fu_441_p3, "isNeg_fu_441_p3");
    sc_trace(mVcdFile, isNeg_reg_629, "isNeg_reg_629");
    sc_trace(mVcdFile, sh_assign_1_cast_fu_467_p1, "sh_assign_1_cast_fu_467_p1");
    sc_trace(mVcdFile, sh_assign_1_cast_reg_634, "sh_assign_1_cast_reg_634");
    sc_trace(mVcdFile, tmp_reg_639, "tmp_reg_639");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_start, "grp_master_ip_mainFunction_fu_143_ap_start");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_done, "grp_master_ip_mainFunction_fu_143_ap_done");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_idle, "grp_master_ip_mainFunction_fu_143_ap_idle");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_ready, "grp_master_ip_mainFunction_fu_143_ap_ready");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_ce, "grp_master_ip_mainFunction_fu_143_ap_ce");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o_ap_vld, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o_ap_vld, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o_ap_vld, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o_ap_vld, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o_ap_vld, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o_ap_vld, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o_ap_vld, "grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_input_V_read, "grp_master_ip_mainFunction_fu_143_input_V_read");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_p_read, "grp_master_ip_mainFunction_fu_143_p_read");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_p_read2, "grp_master_ip_mainFunction_fu_143_p_read2");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_p_read5, "grp_master_ip_mainFunction_fu_143_p_read5");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_return_0, "grp_master_ip_mainFunction_fu_143_ap_return_0");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_return_1, "grp_master_ip_mainFunction_fu_143_ap_return_1");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_return_2, "grp_master_ip_mainFunction_fu_143_ap_return_2");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_return_3, "grp_master_ip_mainFunction_fu_143_ap_return_3");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_return_4, "grp_master_ip_mainFunction_fu_143_ap_return_4");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_return_5, "grp_master_ip_mainFunction_fu_143_ap_return_5");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_return_6, "grp_master_ip_mainFunction_fu_143_ap_return_6");
    sc_trace(mVcdFile, grp_master_ip_mainFunction_fu_143_ap_start_ap_start_reg, "grp_master_ip_mainFunction_fu_143_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start, "ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start");
    sc_trace(mVcdFile, grp_fu_178_p0, "grp_fu_178_p0");
    sc_trace(mVcdFile, grp_fu_178_p1, "grp_fu_178_p1");
    sc_trace(mVcdFile, grp_fu_182_p0, "grp_fu_182_p0");
    sc_trace(mVcdFile, grp_fu_182_p1, "grp_fu_182_p1");
    sc_trace(mVcdFile, grp_fu_190_p0, "grp_fu_190_p0");
    sc_trace(mVcdFile, p_Val2_s_fu_398_p1, "p_Val2_s_fu_398_p1");
    sc_trace(mVcdFile, loc_V_1_fu_419_p1, "loc_V_1_fu_419_p1");
    sc_trace(mVcdFile, loc_V_fu_409_p4, "loc_V_fu_409_p4");
    sc_trace(mVcdFile, tmp_i_i_i_i_cast1_fu_431_p1, "tmp_i_i_i_i_cast1_fu_431_p1");
    sc_trace(mVcdFile, sh_assign_fu_435_p2, "sh_assign_fu_435_p2");
    sc_trace(mVcdFile, tmp_i_i_i_13_fu_449_p2, "tmp_i_i_i_13_fu_449_p2");
    sc_trace(mVcdFile, tmp_i_i_i_cast_fu_455_p1, "tmp_i_i_i_cast_fu_455_p1");
    sc_trace(mVcdFile, sh_assign_1_fu_459_p3, "sh_assign_1_fu_459_p3");
    sc_trace(mVcdFile, tmp_88_i_i_i_cast_fu_471_p1, "tmp_88_i_i_i_cast_fu_471_p1");
    sc_trace(mVcdFile, tmp_89_i_i_i_fu_475_p2, "tmp_89_i_i_i_fu_475_p2");
    sc_trace(mVcdFile, tmp_i_i_i_fu_489_p1, "tmp_i_i_i_fu_489_p1");
    sc_trace(mVcdFile, tmp_88_i_i_i_fu_492_p1, "tmp_88_i_i_i_fu_492_p1");
    sc_trace(mVcdFile, tmp_91_i_i_i_fu_495_p2, "tmp_91_i_i_i_fu_495_p2");
    sc_trace(mVcdFile, tmp_3_fu_501_p1, "tmp_3_fu_501_p1");
    sc_trace(mVcdFile, tmp_4_fu_504_p4, "tmp_4_fu_504_p4");
    sc_trace(mVcdFile, p_Val2_3_fu_514_p3, "p_Val2_3_fu_514_p3");
    sc_trace(mVcdFile, p_Val2_7_i_i_i_fu_521_p2, "p_Val2_7_i_i_i_fu_521_p2");
    sc_trace(mVcdFile, p_Val2_5_fu_527_p3, "p_Val2_5_fu_527_p3");
    sc_trace(mVcdFile, grp_fu_178_ce, "grp_fu_178_ce");
    sc_trace(mVcdFile, grp_fu_182_ce, "grp_fu_182_ce");
    sc_trace(mVcdFile, grp_fu_186_ce, "grp_fu_186_ce");
    sc_trace(mVcdFile, grp_fu_190_ce, "grp_fu_190_ce");
    sc_trace(mVcdFile, grp_fu_193_ce, "grp_fu_193_ce");
    sc_trace(mVcdFile, grp_fu_196_ce, "grp_fu_196_ce");
    sc_trace(mVcdFile, ap_sig_pprstidle_pp0, "ap_sig_pprstidle_pp0");
#endif

    }
    mHdltvinHandle.open("master_ip.hdltvin.dat");
    mHdltvoutHandle.open("master_ip.hdltvout.dat");
}

master_ip::~master_ip() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete master_ip_AXILiteS_s_axi_U;
    delete grp_master_ip_mainFunction_fu_143;
    delete master_ip_dadd_64ns_64ns_64_4_full_dsp_U31;
    delete master_ip_dmul_64ns_64ns_64_4_max_dsp_U32;
    delete master_ip_dmul_64ns_64ns_64_4_max_dsp_U33;
    delete master_ip_sitodp_32ns_64_3_U34;
    delete master_ip_sitodp_32ns_64_3_U35;
    delete master_ip_dsqrt_64ns_64ns_64_17_U36;
}

void master_ip::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_pp0_stg0_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it1 = ap_reg_ppiten_pp0_it0.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it10 = ap_reg_ppiten_pp0_it9.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it11 = ap_reg_ppiten_pp0_it10.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it12 = ap_reg_ppiten_pp0_it11.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it13 = ap_reg_ppiten_pp0_it12.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it14 = ap_reg_ppiten_pp0_it13.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it15 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it15 = ap_reg_ppiten_pp0_it14.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it16 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it16 = ap_reg_ppiten_pp0_it15.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it17 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it17 = ap_reg_ppiten_pp0_it16.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it18 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it18 = ap_reg_ppiten_pp0_it17.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            ap_reg_ppiten_pp0_it9 = ap_reg_ppiten_pp0_it8.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_master_ip_mainFunction_fu_143_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
            grp_master_ip_mainFunction_fu_143_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_ap_ready.read())) {
            grp_master_ip_mainFunction_fu_143_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
        ap_reg_ppstg_tmp_102_i_reg_599_pp0_it6 = tmp_102_i_reg_599.read();
        ap_reg_ppstg_tmp_102_i_reg_599_pp0_it7 = ap_reg_ppstg_tmp_102_i_reg_599_pp0_it6.read();
        isNeg_reg_629 = sh_assign_fu_435_p2.read().range(11, 11);
        p_Result_1_reg_624 = p_Result_1_fu_423_p3.read();
        p_Result_s_reg_619 = p_Val2_s_fu_398_p1.read().range(63, 63);
        sh_assign_1_cast_reg_634 = sh_assign_1_cast_fu_467_p1.read();
        tmp_100_i_reg_566 = tmp_100_i_fu_393_p2.read();
        tmp_96_i_reg_561 = tmp_96_i_fu_388_p2.read();
        tmp_i_reg_556 = tmp_i_fu_383_p2.read();
        tmp_reg_639 = tmp_89_i_i_i_fu_475_p2.read().range(52, 52);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1))) {
        coordinates1_0 = grp_master_ip_mainFunction_fu_143_ap_return_4.read();
        coordinates1_1 = grp_master_ip_mainFunction_fu_143_ap_return_5.read();
        coordinates1_2 = grp_master_ip_mainFunction_fu_143_ap_return_6.read();
        newret7_reg_541 = grp_master_ip_mainFunction_fu_143_ap_return_4.read();
        newret8_reg_546 = grp_master_ip_mainFunction_fu_143_ap_return_5.read();
        newret9_reg_551 = grp_master_ip_mainFunction_fu_143_ap_return_6.read();
        signal1_ck_a_V = grp_master_ip_mainFunction_fu_143_ap_return_0.read();
        signal1_ck_b_V = grp_master_ip_mainFunction_fu_143_ap_return_1.read();
        signal1_current_out_byte_V = grp_master_ip_mainFunction_fu_143_ap_return_2.read();
        signal1_gnss_state_V = grp_master_ip_mainFunction_fu_143_ap_return_3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
        coordinates2_0 = grp_master_ip_mainFunction_fu_143_ap_return_4.read();
        coordinates2_1 = grp_master_ip_mainFunction_fu_143_ap_return_5.read();
        coordinates2_2 = grp_master_ip_mainFunction_fu_143_ap_return_6.read();
        signal2_ck_a_V = grp_master_ip_mainFunction_fu_143_ap_return_0.read();
        signal2_ck_b_V = grp_master_ip_mainFunction_fu_143_ap_return_1.read();
        signal2_current_out_byte_V = grp_master_ip_mainFunction_fu_143_ap_return_2.read();
        signal2_gnss_state_V = grp_master_ip_mainFunction_fu_143_ap_return_3.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o_ap_vld.read())))) {
        signal1_count_V = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o_ap_vld.read())))) {
        signal1_next_out_byte_V = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o_ap_vld.read())))) {
        signal1_previous_input_V = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o_ap_vld.read())))) {
        signal1_tempCoordinates_0 = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o_ap_vld.read())))) {
        signal1_tempCoordinates_1 = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o_ap_vld.read())))) {
        signal1_tempCoordinates_2 = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o_ap_vld.read())))) {
        signal1_uart_state_V = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o_ap_vld.read())))) {
        signal2_count_V = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o_ap_vld.read())))) {
        signal2_next_out_byte_V = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o_ap_vld.read())))) {
        signal2_previous_input_V = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o_ap_vld.read())))) {
        signal2_tempCoordinates_0 = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o_ap_vld.read())))) {
        signal2_tempCoordinates_1 = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o_ap_vld.read())))) {
        signal2_tempCoordinates_2 = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_o.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o_ap_vld.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o_ap_vld.read())))) {
        signal2_uart_state_V = grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_o.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
        tmp_101_i_reg_583 = grp_fu_190_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
        tmp_102_i_reg_599 = grp_fu_182_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it9.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
        tmp_103_i_reg_609 = grp_fu_178_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()))) {
        tmp_95_i_reg_589 = grp_fu_182_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
        tmp_97_i_reg_577 = grp_fu_193_p1.read();
        tmp_98_i_reg_594 = grp_fu_186_p2.read();
        x_assign_reg_614 = grp_fu_196_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it6.read()))) {
        tmp_99_i_reg_604 = grp_fu_178_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()))) {
        tmp_i_12_reg_571 = grp_fu_190_p1.read();
    }
}

void master_ip::thread_alert_V() {
    alert_V = (!p_Val2_5_fu_527_p3.read().is_01() || !ap_const_lv32_3E8.is_01())? sc_lv<1>(): (sc_bigint<32>(p_Val2_5_fu_527_p3.read()) > sc_bigint<32>(ap_const_lv32_3E8));
}

void master_ip::thread_ap_reg_ppiten_pp0_it0() {
    ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
}

void master_ip::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void master_ip::thread_ap_sig_bdd_145() {
    ap_sig_bdd_145 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(0, 0));
}

void master_ip::thread_ap_sig_bdd_93() {
    ap_sig_bdd_93 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(1, 1), ap_const_lv1_1);
}

void master_ip::thread_ap_sig_cseq_ST_pp0_stg0_fsm_0() {
    if (ap_sig_bdd_145.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_0 = ap_const_logic_0;
    }
}

void master_ip::thread_ap_sig_cseq_ST_pp0_stg1_fsm_1() {
    if (ap_sig_bdd_93.read()) {
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg1_fsm_1 = ap_const_logic_0;
    }
}

void master_ip::thread_ap_sig_pprstidle_pp0() {
    if (!esl_seteq<1,1,1>(ap_true, ap_true)) {
        ap_sig_pprstidle_pp0 = ap_const_logic_1;
    } else {
        ap_sig_pprstidle_pp0 = ap_const_logic_0;
    }
}

void master_ip::thread_ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
        ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start = ap_const_logic_1;
    } else {
        ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start = ap_const_logic_0;
    }
}

void master_ip::thread_grp_fu_178_ce() {
    grp_fu_178_ce = ap_const_logic_1;
}

void master_ip::thread_grp_fu_178_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()))) {
        grp_fu_178_p0 = tmp_99_i_reg_604.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
        grp_fu_178_p0 = tmp_95_i_reg_589.read();
    } else {
        grp_fu_178_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void master_ip::thread_grp_fu_178_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it7.read()))) {
        grp_fu_178_p1 = ap_reg_ppstg_tmp_102_i_reg_599_pp0_it7.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
        grp_fu_178_p1 = tmp_98_i_reg_594.read();
    } else {
        grp_fu_178_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void master_ip::thread_grp_fu_182_ce() {
    grp_fu_182_ce = ap_const_logic_1;
}

void master_ip::thread_grp_fu_182_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_fu_182_p0 = tmp_101_i_reg_583.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_fu_182_p0 = tmp_i_12_reg_571.read();
        } else {
            grp_fu_182_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_182_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void master_ip::thread_grp_fu_182_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_fu_182_p1 = tmp_101_i_reg_583.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_fu_182_p1 = tmp_i_12_reg_571.read();
        } else {
            grp_fu_182_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        grp_fu_182_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void master_ip::thread_grp_fu_186_ce() {
    grp_fu_186_ce = ap_const_logic_1;
}

void master_ip::thread_grp_fu_190_ce() {
    grp_fu_190_ce = ap_const_logic_1;
}

void master_ip::thread_grp_fu_190_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read()))) {
        grp_fu_190_p0 = tmp_100_i_reg_566.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        grp_fu_190_p0 = tmp_i_reg_556.read();
    } else {
        grp_fu_190_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void master_ip::thread_grp_fu_193_ce() {
    grp_fu_193_ce = ap_const_logic_1;
}

void master_ip::thread_grp_fu_196_ce() {
    grp_fu_196_ce = ap_const_logic_1;
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_ap_ce() {
    grp_master_ip_mainFunction_fu_143_ap_ce = ap_const_logic_1;
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start.read())) {
        grp_master_ip_mainFunction_fu_143_ap_start = ap_sig_start_in_grp_master_ip_mainFunction_fu_143_ap_start.read();
    } else {
        grp_master_ip_mainFunction_fu_143_ap_start = grp_master_ip_mainFunction_fu_143_ap_start_ap_start_reg.read();
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_input_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_input_V_read = uart2_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_input_V_read = uart1_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_input_V_read =  (sc_lv<1>) ("X");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_input_V_read =  (sc_lv<1>) ("X");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_p_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_p_read = coordinates2_0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_p_read = coordinates1_0.read();
        } else {
            grp_master_ip_mainFunction_fu_143_p_read =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_p_read =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_p_read2() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_p_read2 = coordinates2_1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_p_read2 = coordinates1_1.read();
        } else {
            grp_master_ip_mainFunction_fu_143_p_read2 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_p_read2 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_p_read5() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_p_read5 = coordinates2_2.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_p_read5 = coordinates1_2.read();
        } else {
            grp_master_ip_mainFunction_fu_143_p_read5 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_p_read5 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read = signal2_ck_a_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read = signal1_ck_a_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_a_V_read =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read = signal2_ck_b_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read = signal1_ck_b_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_ck_b_V_read =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i = signal2_count_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i = signal1_count_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_count_V_i =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read = signal2_current_out_byte_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read = signal1_current_out_byte_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_current_out_byte_V_read =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read = signal2_gnss_state_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read = signal1_gnss_state_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read =  (sc_lv<6>) ("XXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_gnss_state_V_read =  (sc_lv<6>) ("XXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i = signal2_next_out_byte_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i = signal1_next_out_byte_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i =  (sc_lv<8>) ("XXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_next_out_byte_V_i =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i = signal2_previous_input_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i = signal1_previous_input_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i =  (sc_lv<1>) ("X");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_previous_input_V_i =  (sc_lv<1>) ("X");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i = signal2_tempCoordinates_0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i = signal1_tempCoordinates_0.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_0_i =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i = signal2_tempCoordinates_1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i = signal1_tempCoordinates_1.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_1_i =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i = signal2_tempCoordinates_2.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i = signal1_tempCoordinates_2.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_tempCoordinates_2_i =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void master_ip::thread_grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_const_logic_1)) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg1_fsm_1.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i = signal2_uart_state_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_0.read())) {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i = signal1_uart_state_V.read();
        } else {
            grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i =  (sc_lv<4>) ("XXXX");
        }
    } else {
        grp_master_ip_mainFunction_fu_143_uart_to_coordinates_uart_state_V_i =  (sc_lv<4>) ("XXXX");
    }
}

void master_ip::thread_isNeg_fu_441_p3() {
    isNeg_fu_441_p3 = sh_assign_fu_435_p2.read().range(11, 11);
}

void master_ip::thread_loc_V_1_fu_419_p1() {
    loc_V_1_fu_419_p1 = p_Val2_s_fu_398_p1.read().range(52-1, 0);
}

void master_ip::thread_loc_V_fu_409_p4() {
    loc_V_fu_409_p4 = p_Val2_s_fu_398_p1.read().range(62, 52);
}

void master_ip::thread_master_ip_AXILiteS_s_axi_U_ap_dummy_ce() {
    master_ip_AXILiteS_s_axi_U_ap_dummy_ce = ap_const_logic_1;
}

void master_ip::thread_p_Result_1_fu_423_p3() {
    p_Result_1_fu_423_p3 = esl_concat<1,52>(ap_const_lv1_1, loc_V_1_fu_419_p1.read());
}

void master_ip::thread_p_Val2_3_fu_514_p3() {
    p_Val2_3_fu_514_p3 = (!isNeg_reg_629.read()[0].is_01())? sc_lv<32>(): ((isNeg_reg_629.read()[0].to_bool())? tmp_3_fu_501_p1.read(): tmp_4_fu_504_p4.read());
}

void master_ip::thread_p_Val2_5_fu_527_p3() {
    p_Val2_5_fu_527_p3 = (!p_Result_s_reg_619.read()[0].is_01())? sc_lv<32>(): ((p_Result_s_reg_619.read()[0].to_bool())? p_Val2_7_i_i_i_fu_521_p2.read(): p_Val2_3_fu_514_p3.read());
}

void master_ip::thread_p_Val2_7_i_i_i_fu_521_p2() {
    p_Val2_7_i_i_i_fu_521_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_3_fu_514_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_3_fu_514_p3.read()));
}

void master_ip::thread_p_Val2_s_fu_398_p1() {
    p_Val2_s_fu_398_p1 = x_assign_reg_614.read();
}

void master_ip::thread_sh_assign_1_cast_fu_467_p1() {
    sh_assign_1_cast_fu_467_p1 = esl_sext<32,12>(sh_assign_1_fu_459_p3.read());
}

void master_ip::thread_sh_assign_1_fu_459_p3() {
    sh_assign_1_fu_459_p3 = (!isNeg_fu_441_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_fu_441_p3.read()[0].to_bool())? tmp_i_i_i_cast_fu_455_p1.read(): sh_assign_fu_435_p2.read());
}

void master_ip::thread_sh_assign_fu_435_p2() {
    sh_assign_fu_435_p2 = (!ap_const_lv12_C01.is_01() || !tmp_i_i_i_i_cast1_fu_431_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(tmp_i_i_i_i_cast1_fu_431_p1.read()));
}

void master_ip::thread_tmp_100_i_fu_393_p2() {
    tmp_100_i_fu_393_p2 = (!newret9_reg_551.read().is_01() || !grp_master_ip_mainFunction_fu_143_ap_return_6.read().is_01())? sc_lv<32>(): (sc_biguint<32>(newret9_reg_551.read()) - sc_biguint<32>(grp_master_ip_mainFunction_fu_143_ap_return_6.read()));
}

void master_ip::thread_tmp_3_fu_501_p1() {
    tmp_3_fu_501_p1 = esl_zext<32,1>(tmp_reg_639.read());
}

void master_ip::thread_tmp_4_fu_504_p4() {
    tmp_4_fu_504_p4 = tmp_91_i_i_i_fu_495_p2.read().range(83, 52);
}

void master_ip::thread_tmp_88_i_i_i_cast_fu_471_p1() {
    tmp_88_i_i_i_cast_fu_471_p1 = esl_zext<53,32>(sh_assign_1_cast_fu_467_p1.read());
}

void master_ip::thread_tmp_88_i_i_i_fu_492_p1() {
    tmp_88_i_i_i_fu_492_p1 = esl_zext<136,32>(sh_assign_1_cast_reg_634.read());
}

void master_ip::thread_tmp_89_i_i_i_fu_475_p2() {
    tmp_89_i_i_i_fu_475_p2 = (!tmp_88_i_i_i_cast_fu_471_p1.read().is_01())? sc_lv<53>(): p_Result_1_fu_423_p3.read() >> (unsigned short)tmp_88_i_i_i_cast_fu_471_p1.read().to_uint();
}

void master_ip::thread_tmp_91_i_i_i_fu_495_p2() {
    tmp_91_i_i_i_fu_495_p2 = (!tmp_88_i_i_i_fu_492_p1.read().is_01())? sc_lv<136>(): tmp_i_i_i_fu_489_p1.read() << (unsigned short)tmp_88_i_i_i_fu_492_p1.read().to_uint();
}

void master_ip::thread_tmp_96_i_fu_388_p2() {
    tmp_96_i_fu_388_p2 = (!newret8_reg_546.read().is_01() || !grp_master_ip_mainFunction_fu_143_ap_return_5.read().is_01())? sc_lv<32>(): (sc_biguint<32>(newret8_reg_546.read()) - sc_biguint<32>(grp_master_ip_mainFunction_fu_143_ap_return_5.read()));
}

void master_ip::thread_tmp_i_fu_383_p2() {
    tmp_i_fu_383_p2 = (!newret7_reg_541.read().is_01() || !grp_master_ip_mainFunction_fu_143_ap_return_4.read().is_01())? sc_lv<32>(): (sc_biguint<32>(newret7_reg_541.read()) - sc_biguint<32>(grp_master_ip_mainFunction_fu_143_ap_return_4.read()));
}

void master_ip::thread_tmp_i_i_i_13_fu_449_p2() {
    tmp_i_i_i_13_fu_449_p2 = (!ap_const_lv11_3FF.is_01() || !loc_V_fu_409_p4.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(loc_V_fu_409_p4.read()));
}

void master_ip::thread_tmp_i_i_i_cast_fu_455_p1() {
    tmp_i_i_i_cast_fu_455_p1 = esl_sext<12,11>(tmp_i_i_i_13_fu_449_p2.read());
}

void master_ip::thread_tmp_i_i_i_fu_489_p1() {
    tmp_i_i_i_fu_489_p1 = esl_zext<136,53>(p_Result_1_reg_624.read());
}

void master_ip::thread_tmp_i_i_i_i_cast1_fu_431_p1() {
    tmp_i_i_i_i_cast1_fu_431_p1 = esl_zext<12,11>(loc_V_fu_409_p4.read());
}

void master_ip::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_pp0_stg1_fsm_1;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_0;
break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

void master_ip::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"uart1_V\" :  \"" << uart1_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"uart2_V\" :  \"" << uart2_V.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"alert_V\" :  \"" << alert_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

