// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _master_ip_mainFunction_HH_
#define _master_ip_mainFunction_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "master_ip_get_gps_info_from_ubx.h"
#include "master_ip_uart_to_byte.h"

namespace ap_rtl {

struct master_ip_mainFunction : public sc_module {
    // Port declarations 43
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > ap_ce;
    sc_in< sc_lv<16> > uart_to_coordinates_count_V_i;
    sc_out< sc_lv<16> > uart_to_coordinates_count_V_o;
    sc_out< sc_logic > uart_to_coordinates_count_V_o_ap_vld;
    sc_in< sc_lv<1> > uart_to_coordinates_previous_input_V_i;
    sc_out< sc_lv<1> > uart_to_coordinates_previous_input_V_o;
    sc_out< sc_logic > uart_to_coordinates_previous_input_V_o_ap_vld;
    sc_in< sc_lv<4> > uart_to_coordinates_uart_state_V_i;
    sc_out< sc_lv<4> > uart_to_coordinates_uart_state_V_o;
    sc_out< sc_logic > uart_to_coordinates_uart_state_V_o_ap_vld;
    sc_in< sc_lv<8> > uart_to_coordinates_next_out_byte_V_i;
    sc_out< sc_lv<8> > uart_to_coordinates_next_out_byte_V_o;
    sc_out< sc_logic > uart_to_coordinates_next_out_byte_V_o_ap_vld;
    sc_in< sc_lv<8> > uart_to_coordinates_current_out_byte_V_read;
    sc_in< sc_lv<6> > uart_to_coordinates_gnss_state_V_read;
    sc_in< sc_lv<8> > uart_to_coordinates_ck_a_V_read;
    sc_in< sc_lv<8> > uart_to_coordinates_ck_b_V_read;
    sc_in< sc_lv<32> > uart_to_coordinates_tempCoordinates_0_i;
    sc_out< sc_lv<32> > uart_to_coordinates_tempCoordinates_0_o;
    sc_out< sc_logic > uart_to_coordinates_tempCoordinates_0_o_ap_vld;
    sc_in< sc_lv<32> > uart_to_coordinates_tempCoordinates_1_i;
    sc_out< sc_lv<32> > uart_to_coordinates_tempCoordinates_1_o;
    sc_out< sc_logic > uart_to_coordinates_tempCoordinates_1_o_ap_vld;
    sc_in< sc_lv<32> > uart_to_coordinates_tempCoordinates_2_i;
    sc_out< sc_lv<32> > uart_to_coordinates_tempCoordinates_2_o;
    sc_out< sc_logic > uart_to_coordinates_tempCoordinates_2_o_ap_vld;
    sc_in< sc_lv<1> > input_V_read;
    sc_in< sc_lv<32> > p_read;
    sc_in< sc_lv<32> > p_read2;
    sc_in< sc_lv<32> > p_read5;
    sc_out< sc_lv<8> > ap_return_0;
    sc_out< sc_lv<8> > ap_return_1;
    sc_out< sc_lv<8> > ap_return_2;
    sc_out< sc_lv<6> > ap_return_3;
    sc_out< sc_lv<32> > ap_return_4;
    sc_out< sc_lv<32> > ap_return_5;
    sc_out< sc_lv<32> > ap_return_6;


    // Module declarations
    master_ip_mainFunction(sc_module_name name);
    SC_HAS_PROCESS(master_ip_mainFunction);

    ~master_ip_mainFunction();

    sc_trace_file* mVcdFile;

    master_ip_get_gps_info_from_ubx* call_ret5_master_ip_get_gps_info_from_ubx_fu_166;
    master_ip_uart_to_byte* call_ret6_master_ip_uart_to_byte_fu_187;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_0;
    sc_signal< bool > ap_sig_bdd_19;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<1> > tmp_fu_203_p1;
    sc_signal< sc_lv<1> > tmp_reg_453;
    sc_signal< sc_lv<8> > uart_to_coordinates_current_ou_reg_457;
    sc_signal< sc_lv<8> > uart_to_coordinates_ck_a_V_1_i_fu_348_p3;
    sc_signal< sc_lv<8> > uart_to_coordinates_ck_a_V_1_i_reg_462;
    sc_signal< sc_lv<8> > uart_to_coordinates_ck_b_V_1_i_fu_357_p3;
    sc_signal< sc_lv<8> > uart_to_coordinates_ck_b_V_1_i_reg_467;
    sc_signal< sc_lv<6> > call_ret2_reg_472;
    sc_signal< sc_lv<32> > coordinates_0_ret_reg_477;
    sc_signal< sc_lv<32> > coordinates_1_ret_reg_482;
    sc_signal< sc_lv<32> > coordinates_2_ret_reg_487;
    sc_signal< sc_lv<8> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read;
    sc_signal< sc_lv<6> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read;
    sc_signal< sc_lv<8> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read;
    sc_signal< sc_lv<8> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o;
    sc_signal< sc_logic > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o;
    sc_signal< sc_logic > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o;
    sc_signal< sc_logic > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_p_read1;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_p_read4;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_p_read5;
    sc_signal< sc_lv<6> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2;
    sc_signal< sc_lv<32> > call_ret5_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3;
    sc_signal< sc_lv<16> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_count_V_i;
    sc_signal< sc_lv<16> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_count_V_o;
    sc_signal< sc_logic > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_count_V_o_ap_vld;
    sc_signal< sc_lv<1> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_previous_input_V_i;
    sc_signal< sc_lv<1> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_previous_input_V_o;
    sc_signal< sc_logic > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_previous_input_V_o_ap_vld;
    sc_signal< sc_lv<1> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_current_input_V_read;
    sc_signal< sc_lv<4> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_uart_state_V_i;
    sc_signal< sc_lv<4> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_uart_state_V_o;
    sc_signal< sc_logic > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_uart_state_V_o_ap_vld;
    sc_signal< sc_lv<8> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_next_out_byte_V_i;
    sc_signal< sc_lv<8> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_next_out_byte_V_o;
    sc_signal< sc_logic > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_next_out_byte_V_o_ap_vld;
    sc_signal< sc_lv<8> > call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_current_out_byte_V_read;
    sc_signal< sc_lv<1> > call_ret6_master_ip_uart_to_byte_fu_187_ap_return_0;
    sc_signal< sc_lv<8> > call_ret6_master_ip_uart_to_byte_fu_187_ap_return_1;
    sc_signal< sc_lv<32> > ap_reg_phiprechg_coordinates_reg_112pp0_it0;
    sc_signal< sc_lv<32> > ap_reg_phiprechg_coordinates_reg_112pp0_it1;
    sc_signal< sc_lv<32> > coordinates_phi_fu_115_p4;
    sc_signal< sc_lv<32> > ap_reg_phiprechg_coordinates_1_reg_121pp0_it0;
    sc_signal< sc_lv<32> > ap_reg_phiprechg_coordinates_1_reg_121pp0_it1;
    sc_signal< sc_lv<32> > coordinates_1_phi_fu_124_p4;
    sc_signal< sc_lv<32> > ap_reg_phiprechg_coordinates_2_reg_130pp0_it0;
    sc_signal< sc_lv<32> > ap_reg_phiprechg_coordinates_2_reg_130pp0_it1;
    sc_signal< sc_lv<32> > coordinates_2_phi_fu_133_p4;
    sc_signal< sc_lv<8> > ap_reg_phiprechg_uart_to_coordinates_ck_a_V_reg_139pp0_it0;
    sc_signal< sc_lv<8> > ap_reg_phiprechg_uart_to_coordinates_ck_a_V_reg_139pp0_it1;
    sc_signal< sc_lv<8> > uart_to_coordinates_ck_a_V_phi_fu_142_p4;
    sc_signal< sc_lv<8> > ap_reg_phiprechg_uart_to_coordinates_ck_b_V_reg_148pp0_it0;
    sc_signal< sc_lv<8> > ap_reg_phiprechg_uart_to_coordinates_ck_b_V_reg_148pp0_it1;
    sc_signal< sc_lv<8> > uart_to_coordinates_ck_b_V_phi_fu_151_p4;
    sc_signal< sc_lv<6> > ap_reg_phiprechg_uart_to_coordinates_gnss_state_reg_157pp0_it0;
    sc_signal< sc_lv<6> > ap_reg_phiprechg_uart_to_coordinates_gnss_state_reg_157pp0_it1;
    sc_signal< sc_lv<6> > uart_to_coordinates_gnss_state_phi_fu_160_p4;
    sc_signal< sc_lv<8> > tmp_i_fu_212_p2;
    sc_signal< sc_lv<1> > tmp_86_i_fu_224_p2;
    sc_signal< sc_lv<1> > tmp_87_i_fu_230_p2;
    sc_signal< sc_lv<1> > or_cond4_i_fu_236_p2;
    sc_signal< sc_lv<1> > sel_tmp5_fu_288_p2;
    sc_signal< sc_lv<1> > sel_tmp6_fu_294_p2;
    sc_signal< sc_lv<1> > sel_tmp4_fu_282_p2;
    sc_signal< sc_lv<1> > sel_tmp3_fu_276_p2;
    sc_signal< sc_lv<1> > tmp7_fu_312_p2;
    sc_signal< sc_lv<1> > tmp6_fu_306_p2;
    sc_signal< sc_lv<1> > sel_tmp_fu_258_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_270_p2;
    sc_signal< sc_lv<1> > sel_tmp1_fu_264_p2;
    sc_signal< sc_lv<1> > sel_tmp7_fu_300_p2;
    sc_signal< sc_lv<1> > tmp10_fu_330_p2;
    sc_signal< sc_lv<1> > tmp9_fu_324_p2;
    sc_signal< sc_lv<1> > tmp11_fu_336_p2;
    sc_signal< sc_lv<1> > tmp8_fu_318_p2;
    sc_signal< sc_lv<1> > sel_tmp8_fu_342_p2;
    sc_signal< sc_lv<8> > uart_to_coordinates_ck_a_V_rea_fu_242_p3;
    sc_signal< sc_lv<8> > uart_to_coordinates_ck_b_V_rea_fu_250_p3;
    sc_signal< sc_lv<8> > tmp_85_i_fu_218_p2;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< sc_logic > ap_sig_pprstidle_pp0;
    sc_signal< bool > ap_sig_bdd_42;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_pp0_stg0_fsm_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<6> ap_const_lv6_39;
    static const sc_lv<6> ap_const_lv6_3C;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<6> ap_const_lv6_3F;
    static const sc_lv<6> ap_const_lv6_3E;
    static const sc_lv<6> ap_const_lv6_3D;
    static const sc_lv<6> ap_const_lv6_3B;
    static const sc_lv<6> ap_const_lv6_3A;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<6> ap_const_lv6_0;
    static const bool ap_true;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_reg_phiprechg_coordinates_1_reg_121pp0_it0();
    void thread_ap_reg_phiprechg_coordinates_2_reg_130pp0_it0();
    void thread_ap_reg_phiprechg_coordinates_reg_112pp0_it0();
    void thread_ap_reg_phiprechg_uart_to_coordinates_ck_a_V_reg_139pp0_it0();
    void thread_ap_reg_phiprechg_uart_to_coordinates_ck_b_V_reg_148pp0_it0();
    void thread_ap_reg_phiprechg_uart_to_coordinates_gnss_state_reg_157pp0_it0();
    void thread_ap_reg_ppiten_pp0_it0();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_sig_bdd_19();
    void thread_ap_sig_bdd_42();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_0();
    void thread_ap_sig_pprstidle_pp0();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_p_read1();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_p_read4();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_p_read5();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i();
    void thread_call_ret5_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i();
    void thread_call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_count_V_i();
    void thread_call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_current_input_V_read();
    void thread_call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_current_out_byte_V_read();
    void thread_call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_next_out_byte_V_i();
    void thread_call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_previous_input_V_i();
    void thread_call_ret6_master_ip_uart_to_byte_fu_187_uart_to_coordinates_uart_state_V_i();
    void thread_coordinates_1_phi_fu_124_p4();
    void thread_coordinates_2_phi_fu_133_p4();
    void thread_coordinates_phi_fu_115_p4();
    void thread_or_cond4_i_fu_236_p2();
    void thread_sel_tmp1_fu_264_p2();
    void thread_sel_tmp2_fu_270_p2();
    void thread_sel_tmp3_fu_276_p2();
    void thread_sel_tmp4_fu_282_p2();
    void thread_sel_tmp5_fu_288_p2();
    void thread_sel_tmp6_fu_294_p2();
    void thread_sel_tmp7_fu_300_p2();
    void thread_sel_tmp8_fu_342_p2();
    void thread_sel_tmp_fu_258_p2();
    void thread_tmp10_fu_330_p2();
    void thread_tmp11_fu_336_p2();
    void thread_tmp6_fu_306_p2();
    void thread_tmp7_fu_312_p2();
    void thread_tmp8_fu_318_p2();
    void thread_tmp9_fu_324_p2();
    void thread_tmp_85_i_fu_218_p2();
    void thread_tmp_86_i_fu_224_p2();
    void thread_tmp_87_i_fu_230_p2();
    void thread_tmp_fu_203_p1();
    void thread_tmp_i_fu_212_p2();
    void thread_uart_to_coordinates_ck_a_V_1_i_fu_348_p3();
    void thread_uart_to_coordinates_ck_a_V_phi_fu_142_p4();
    void thread_uart_to_coordinates_ck_a_V_rea_fu_242_p3();
    void thread_uart_to_coordinates_ck_b_V_1_i_fu_357_p3();
    void thread_uart_to_coordinates_ck_b_V_phi_fu_151_p4();
    void thread_uart_to_coordinates_ck_b_V_rea_fu_250_p3();
    void thread_uart_to_coordinates_count_V_o();
    void thread_uart_to_coordinates_count_V_o_ap_vld();
    void thread_uart_to_coordinates_gnss_state_phi_fu_160_p4();
    void thread_uart_to_coordinates_next_out_byte_V_o();
    void thread_uart_to_coordinates_next_out_byte_V_o_ap_vld();
    void thread_uart_to_coordinates_previous_input_V_o();
    void thread_uart_to_coordinates_previous_input_V_o_ap_vld();
    void thread_uart_to_coordinates_tempCoordinates_0_o();
    void thread_uart_to_coordinates_tempCoordinates_0_o_ap_vld();
    void thread_uart_to_coordinates_tempCoordinates_1_o();
    void thread_uart_to_coordinates_tempCoordinates_1_o_ap_vld();
    void thread_uart_to_coordinates_tempCoordinates_2_o();
    void thread_uart_to_coordinates_tempCoordinates_2_o_ap_vld();
    void thread_uart_to_coordinates_uart_state_V_o();
    void thread_uart_to_coordinates_uart_state_V_o_ap_vld();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
