// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "master_ip_mainFunction.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic master_ip_mainFunction::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic master_ip_mainFunction::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> master_ip_mainFunction::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> master_ip_mainFunction::ap_ST_st2_fsm_1 = "10";
const sc_lv<3> master_ip_mainFunction::ap_ST_st3_fsm_2 = "100";
const sc_lv<32> master_ip_mainFunction::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> master_ip_mainFunction::ap_const_lv1_1 = "1";
const sc_lv<32> master_ip_mainFunction::ap_const_lv32_1 = "1";
const sc_lv<1> master_ip_mainFunction::ap_const_lv1_0 = "0";
const sc_lv<32> master_ip_mainFunction::ap_const_lv32_2 = "10";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_39 = "111001";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_3C = "111100";
const sc_lv<8> master_ip_mainFunction::ap_const_lv8_0 = "00000000";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_3F = "111111";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_3E = "111110";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_3D = "111101";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_3B = "111011";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_3A = "111010";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_1 = "1";
const sc_lv<6> master_ip_mainFunction::ap_const_lv6_0 = "000000";

master_ip_mainFunction::master_ip_mainFunction(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_master_ip_get_gps_info_from_ubx_fu_166 = new master_ip_get_gps_info_from_ubx("grp_master_ip_get_gps_info_from_ubx_fu_166");
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_clk(ap_clk);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_rst(ap_rst);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_start(grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_done(grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_idle(grp_master_ip_get_gps_info_from_ubx_fu_166_ap_idle);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_ready(grp_master_ip_get_gps_info_from_ubx_fu_166_ap_ready);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_current_out_byte_V_read(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_gnss_state_V_read(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_ck_a_V_read(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_ck_b_V_read(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_0_i(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_0_o(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_0_o_ap_vld(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_1_i(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_1_o(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_1_o_ap_vld(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_2_i(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_2_o(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o);
    grp_master_ip_get_gps_info_from_ubx_fu_166->uart_to_coordinates_tempCoordinates_2_o_ap_vld(grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld);
    grp_master_ip_get_gps_info_from_ubx_fu_166->p_read1(grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1);
    grp_master_ip_get_gps_info_from_ubx_fu_166->p_read4(grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4);
    grp_master_ip_get_gps_info_from_ubx_fu_166->p_read5(grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_return_0(grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_return_1(grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_return_2(grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2);
    grp_master_ip_get_gps_info_from_ubx_fu_166->ap_return_3(grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3);
    call_ret6_master_ip_uart_to_byte_fu_183 = new master_ip_uart_to_byte("call_ret6_master_ip_uart_to_byte_fu_183");
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_count_V_i(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_count_V_o(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_count_V_o_ap_vld(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_previous_input_V_i(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_previous_input_V_o(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_previous_input_V_o_ap_vld(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_current_input_V_read(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_uart_state_V_i(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_uart_state_V_o(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_uart_state_V_o_ap_vld(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_next_out_byte_V_i(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_next_out_byte_V_o(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_next_out_byte_V_o_ap_vld(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld);
    call_ret6_master_ip_uart_to_byte_fu_183->uart_to_coordinates_current_out_byte_V_read(call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read);
    call_ret6_master_ip_uart_to_byte_fu_183->ap_return_0(call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0);
    call_ret6_master_ip_uart_to_byte_fu_183->ap_return_1(call_ret6_master_ip_uart_to_byte_fu_183_ap_return_1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( uart_to_coordinates_ck_a_V_phi_fu_142_p4 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( uart_to_coordinates_ck_b_V_phi_fu_151_p4 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( tmp_reg_455 );
    sensitive << ( uart_to_coordinates_current_ou_reg_459 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_return_2_preg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( uart_to_coordinates_gnss_state_phi_fu_160_p4 );
    sensitive << ( ap_return_3_preg );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( coordinates_phi_fu_115_p4 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_return_4_preg );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( coordinates_1_phi_fu_124_p4 );
    sensitive << ( ap_return_5_preg );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( coordinates_2_phi_fu_133_p4 );
    sensitive << ( ap_return_6_preg );

    SC_METHOD(thread_ap_sig_bdd_148);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_89);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_89 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_148 );

    SC_METHOD(thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_count_V_i );

    SC_METHOD(thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( input_V_read );

    SC_METHOD(thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );

    SC_METHOD(thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_next_out_byte_V_i );

    SC_METHOD(thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_previous_input_V_i );

    SC_METHOD(thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_uart_state_V_i );

    SC_METHOD(thread_coordinates_1_phi_fu_124_p4);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( coordinates_1_reg_121 );

    SC_METHOD(thread_coordinates_2_phi_fu_133_p4);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( coordinates_2_reg_130 );

    SC_METHOD(thread_coordinates_phi_fu_115_p4);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1 );
    sensitive << ( coordinates_reg_112 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start);
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1);
    sensitive << ( p_read );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4);
    sensitive << ( p_read2 );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5);
    sensitive << ( p_read5 );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read);
    sensitive << ( tmp_reg_455 );
    sensitive << ( uart_to_coordinates_ck_a_V_1_i_reg_466 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read);
    sensitive << ( tmp_reg_455 );
    sensitive << ( uart_to_coordinates_ck_b_V_1_i_reg_472 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read);
    sensitive << ( tmp_reg_455 );
    sensitive << ( uart_to_coordinates_current_ou_reg_459 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i);
    sensitive << ( uart_to_coordinates_tempCoordinates_0_i );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i);
    sensitive << ( uart_to_coordinates_tempCoordinates_1_i );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i);
    sensitive << ( uart_to_coordinates_tempCoordinates_2_i );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_or_cond4_i_fu_226_p2);
    sensitive << ( tmp_86_i_fu_216_p2 );
    sensitive << ( tmp_87_i_fu_221_p2 );

    SC_METHOD(thread_sel_tmp1_fu_251_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sel_tmp2_fu_256_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sel_tmp3_fu_261_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sel_tmp4_fu_266_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sel_tmp5_fu_271_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sel_tmp6_fu_276_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sel_tmp7_fu_281_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_sel_tmp8_fu_322_p2);
    sensitive << ( tmp11_fu_316_p2 );
    sensitive << ( tmp8_fu_298_p2 );

    SC_METHOD(thread_sel_tmp_fu_246_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp10_fu_310_p2);
    sensitive << ( sel_tmp1_fu_251_p2 );
    sensitive << ( sel_tmp7_fu_281_p2 );

    SC_METHOD(thread_tmp11_fu_316_p2);
    sensitive << ( tmp10_fu_310_p2 );
    sensitive << ( tmp9_fu_304_p2 );

    SC_METHOD(thread_tmp6_fu_286_p2);
    sensitive << ( sel_tmp5_fu_271_p2 );
    sensitive << ( sel_tmp6_fu_276_p2 );

    SC_METHOD(thread_tmp7_fu_292_p2);
    sensitive << ( sel_tmp4_fu_266_p2 );
    sensitive << ( sel_tmp3_fu_261_p2 );

    SC_METHOD(thread_tmp8_fu_298_p2);
    sensitive << ( tmp7_fu_292_p2 );
    sensitive << ( tmp6_fu_286_p2 );

    SC_METHOD(thread_tmp9_fu_304_p2);
    sensitive << ( sel_tmp_fu_246_p2 );
    sensitive << ( sel_tmp2_fu_256_p2 );

    SC_METHOD(thread_tmp_85_i_fu_211_p2);
    sensitive << ( uart_to_coordinates_ck_b_V_read );
    sensitive << ( tmp_i_fu_207_p2 );

    SC_METHOD(thread_tmp_86_i_fu_216_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp_87_i_fu_221_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp_fu_199_p1);
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0 );

    SC_METHOD(thread_tmp_i_fu_207_p2);
    sensitive << ( uart_to_coordinates_ck_a_V_read );
    sensitive << ( uart_to_coordinates_current_ou_reg_459 );

    SC_METHOD(thread_uart_to_coordinates_ck_a_V_1_i_fu_328_p3);
    sensitive << ( tmp_i_fu_207_p2 );
    sensitive << ( sel_tmp8_fu_322_p2 );
    sensitive << ( uart_to_coordinates_ck_a_V_rea_fu_232_p3 );

    SC_METHOD(thread_uart_to_coordinates_ck_a_V_phi_fu_142_p4);
    sensitive << ( tmp_reg_455 );
    sensitive << ( uart_to_coordinates_ck_a_V_1_i_reg_466 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( uart_to_coordinates_ck_a_V_reg_139 );

    SC_METHOD(thread_uart_to_coordinates_ck_a_V_rea_fu_232_p3);
    sensitive << ( uart_to_coordinates_ck_a_V_read );
    sensitive << ( or_cond4_i_fu_226_p2 );

    SC_METHOD(thread_uart_to_coordinates_ck_b_V_1_i_fu_337_p3);
    sensitive << ( sel_tmp8_fu_322_p2 );
    sensitive << ( uart_to_coordinates_ck_b_V_rea_fu_239_p3 );
    sensitive << ( tmp_85_i_fu_211_p2 );

    SC_METHOD(thread_uart_to_coordinates_ck_b_V_phi_fu_151_p4);
    sensitive << ( tmp_reg_455 );
    sensitive << ( uart_to_coordinates_ck_b_V_1_i_reg_472 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( uart_to_coordinates_ck_b_V_reg_148 );

    SC_METHOD(thread_uart_to_coordinates_ck_b_V_rea_fu_239_p3);
    sensitive << ( uart_to_coordinates_ck_b_V_read );
    sensitive << ( or_cond4_i_fu_226_p2 );

    SC_METHOD(thread_uart_to_coordinates_count_V_o);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_count_V_i );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld );

    SC_METHOD(thread_uart_to_coordinates_count_V_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld );

    SC_METHOD(thread_uart_to_coordinates_gnss_state_phi_fu_160_p4);
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( uart_to_coordinates_gnss_state_reg_157 );

    SC_METHOD(thread_uart_to_coordinates_next_out_byte_V_o);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_next_out_byte_V_i );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld );

    SC_METHOD(thread_uart_to_coordinates_next_out_byte_V_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld );

    SC_METHOD(thread_uart_to_coordinates_previous_input_V_o);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_previous_input_V_i );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld );

    SC_METHOD(thread_uart_to_coordinates_previous_input_V_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_0_o);
    sensitive << ( uart_to_coordinates_tempCoordinates_0_i );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_0_o_ap_vld);
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_1_o);
    sensitive << ( uart_to_coordinates_tempCoordinates_1_i );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_1_o_ap_vld);
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_2_o);
    sensitive << ( uart_to_coordinates_tempCoordinates_2_i );
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_2_o_ap_vld);
    sensitive << ( tmp_reg_455 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_uart_to_coordinates_uart_state_V_o);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_uart_state_V_i );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld );

    SC_METHOD(thread_uart_to_coordinates_uart_state_V_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_199_p1 );
    sensitive << ( tmp_reg_455 );
    sensitive << ( grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done );

    ap_CS_fsm = "001";
    grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg = SC_LOGIC_0;
    ap_return_0_preg = "00000000";
    ap_return_1_preg = "00000000";
    ap_return_2_preg = "00000000";
    ap_return_3_preg = "000000";
    ap_return_4_preg = "00000000000000000000000000000000";
    ap_return_5_preg = "00000000000000000000000000000000";
    ap_return_6_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "master_ip_mainFunction_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, uart_to_coordinates_count_V_i, "(port)uart_to_coordinates_count_V_i");
    sc_trace(mVcdFile, uart_to_coordinates_count_V_o, "(port)uart_to_coordinates_count_V_o");
    sc_trace(mVcdFile, uart_to_coordinates_count_V_o_ap_vld, "(port)uart_to_coordinates_count_V_o_ap_vld");
    sc_trace(mVcdFile, uart_to_coordinates_previous_input_V_i, "(port)uart_to_coordinates_previous_input_V_i");
    sc_trace(mVcdFile, uart_to_coordinates_previous_input_V_o, "(port)uart_to_coordinates_previous_input_V_o");
    sc_trace(mVcdFile, uart_to_coordinates_previous_input_V_o_ap_vld, "(port)uart_to_coordinates_previous_input_V_o_ap_vld");
    sc_trace(mVcdFile, uart_to_coordinates_uart_state_V_i, "(port)uart_to_coordinates_uart_state_V_i");
    sc_trace(mVcdFile, uart_to_coordinates_uart_state_V_o, "(port)uart_to_coordinates_uart_state_V_o");
    sc_trace(mVcdFile, uart_to_coordinates_uart_state_V_o_ap_vld, "(port)uart_to_coordinates_uart_state_V_o_ap_vld");
    sc_trace(mVcdFile, uart_to_coordinates_next_out_byte_V_i, "(port)uart_to_coordinates_next_out_byte_V_i");
    sc_trace(mVcdFile, uart_to_coordinates_next_out_byte_V_o, "(port)uart_to_coordinates_next_out_byte_V_o");
    sc_trace(mVcdFile, uart_to_coordinates_next_out_byte_V_o_ap_vld, "(port)uart_to_coordinates_next_out_byte_V_o_ap_vld");
    sc_trace(mVcdFile, uart_to_coordinates_current_out_byte_V_read, "(port)uart_to_coordinates_current_out_byte_V_read");
    sc_trace(mVcdFile, uart_to_coordinates_gnss_state_V_read, "(port)uart_to_coordinates_gnss_state_V_read");
    sc_trace(mVcdFile, uart_to_coordinates_ck_a_V_read, "(port)uart_to_coordinates_ck_a_V_read");
    sc_trace(mVcdFile, uart_to_coordinates_ck_b_V_read, "(port)uart_to_coordinates_ck_b_V_read");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_0_i, "(port)uart_to_coordinates_tempCoordinates_0_i");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_0_o, "(port)uart_to_coordinates_tempCoordinates_0_o");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_0_o_ap_vld, "(port)uart_to_coordinates_tempCoordinates_0_o_ap_vld");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_1_i, "(port)uart_to_coordinates_tempCoordinates_1_i");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_1_o, "(port)uart_to_coordinates_tempCoordinates_1_o");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_1_o_ap_vld, "(port)uart_to_coordinates_tempCoordinates_1_o_ap_vld");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_2_i, "(port)uart_to_coordinates_tempCoordinates_2_i");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_2_o, "(port)uart_to_coordinates_tempCoordinates_2_o");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_2_o_ap_vld, "(port)uart_to_coordinates_tempCoordinates_2_o_ap_vld");
    sc_trace(mVcdFile, input_V_read, "(port)input_V_read");
    sc_trace(mVcdFile, p_read, "(port)p_read");
    sc_trace(mVcdFile, p_read2, "(port)p_read2");
    sc_trace(mVcdFile, p_read5, "(port)p_read5");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, tmp_fu_199_p1, "tmp_fu_199_p1");
    sc_trace(mVcdFile, tmp_reg_455, "tmp_reg_455");
    sc_trace(mVcdFile, uart_to_coordinates_current_ou_reg_459, "uart_to_coordinates_current_ou_reg_459");
    sc_trace(mVcdFile, uart_to_coordinates_ck_a_V_1_i_fu_328_p3, "uart_to_coordinates_ck_a_V_1_i_fu_328_p3");
    sc_trace(mVcdFile, uart_to_coordinates_ck_a_V_1_i_reg_466, "uart_to_coordinates_ck_a_V_1_i_reg_466");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_89, "ap_sig_bdd_89");
    sc_trace(mVcdFile, uart_to_coordinates_ck_b_V_1_i_fu_337_p3, "uart_to_coordinates_ck_b_V_1_i_fu_337_p3");
    sc_trace(mVcdFile, uart_to_coordinates_ck_b_V_1_i_reg_472, "uart_to_coordinates_ck_b_V_1_i_reg_472");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_idle, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_idle");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_ready, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_ready");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld, "grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1, "grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4, "grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5, "grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read, "call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0, "call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0");
    sc_trace(mVcdFile, call_ret6_master_ip_uart_to_byte_fu_183_ap_return_1, "call_ret6_master_ip_uart_to_byte_fu_183_ap_return_1");
    sc_trace(mVcdFile, coordinates_phi_fu_115_p4, "coordinates_phi_fu_115_p4");
    sc_trace(mVcdFile, coordinates_reg_112, "coordinates_reg_112");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_148, "ap_sig_bdd_148");
    sc_trace(mVcdFile, coordinates_1_phi_fu_124_p4, "coordinates_1_phi_fu_124_p4");
    sc_trace(mVcdFile, coordinates_1_reg_121, "coordinates_1_reg_121");
    sc_trace(mVcdFile, coordinates_2_phi_fu_133_p4, "coordinates_2_phi_fu_133_p4");
    sc_trace(mVcdFile, coordinates_2_reg_130, "coordinates_2_reg_130");
    sc_trace(mVcdFile, uart_to_coordinates_ck_a_V_phi_fu_142_p4, "uart_to_coordinates_ck_a_V_phi_fu_142_p4");
    sc_trace(mVcdFile, uart_to_coordinates_ck_a_V_reg_139, "uart_to_coordinates_ck_a_V_reg_139");
    sc_trace(mVcdFile, uart_to_coordinates_ck_b_V_phi_fu_151_p4, "uart_to_coordinates_ck_b_V_phi_fu_151_p4");
    sc_trace(mVcdFile, uart_to_coordinates_ck_b_V_reg_148, "uart_to_coordinates_ck_b_V_reg_148");
    sc_trace(mVcdFile, uart_to_coordinates_gnss_state_phi_fu_160_p4, "uart_to_coordinates_gnss_state_phi_fu_160_p4");
    sc_trace(mVcdFile, uart_to_coordinates_gnss_state_reg_157, "uart_to_coordinates_gnss_state_reg_157");
    sc_trace(mVcdFile, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg, "grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg");
    sc_trace(mVcdFile, tmp_i_fu_207_p2, "tmp_i_fu_207_p2");
    sc_trace(mVcdFile, tmp_86_i_fu_216_p2, "tmp_86_i_fu_216_p2");
    sc_trace(mVcdFile, tmp_87_i_fu_221_p2, "tmp_87_i_fu_221_p2");
    sc_trace(mVcdFile, or_cond4_i_fu_226_p2, "or_cond4_i_fu_226_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_271_p2, "sel_tmp5_fu_271_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_276_p2, "sel_tmp6_fu_276_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_266_p2, "sel_tmp4_fu_266_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_261_p2, "sel_tmp3_fu_261_p2");
    sc_trace(mVcdFile, tmp7_fu_292_p2, "tmp7_fu_292_p2");
    sc_trace(mVcdFile, tmp6_fu_286_p2, "tmp6_fu_286_p2");
    sc_trace(mVcdFile, sel_tmp_fu_246_p2, "sel_tmp_fu_246_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_256_p2, "sel_tmp2_fu_256_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_251_p2, "sel_tmp1_fu_251_p2");
    sc_trace(mVcdFile, sel_tmp7_fu_281_p2, "sel_tmp7_fu_281_p2");
    sc_trace(mVcdFile, tmp10_fu_310_p2, "tmp10_fu_310_p2");
    sc_trace(mVcdFile, tmp9_fu_304_p2, "tmp9_fu_304_p2");
    sc_trace(mVcdFile, tmp11_fu_316_p2, "tmp11_fu_316_p2");
    sc_trace(mVcdFile, tmp8_fu_298_p2, "tmp8_fu_298_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_322_p2, "sel_tmp8_fu_322_p2");
    sc_trace(mVcdFile, uart_to_coordinates_ck_a_V_rea_fu_232_p3, "uart_to_coordinates_ck_a_V_rea_fu_232_p3");
    sc_trace(mVcdFile, uart_to_coordinates_ck_b_V_rea_fu_239_p3, "uart_to_coordinates_ck_b_V_rea_fu_239_p3");
    sc_trace(mVcdFile, tmp_85_i_fu_211_p2, "tmp_85_i_fu_211_p2");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_return_2_preg, "ap_return_2_preg");
    sc_trace(mVcdFile, ap_return_3_preg, "ap_return_3_preg");
    sc_trace(mVcdFile, ap_return_4_preg, "ap_return_4_preg");
    sc_trace(mVcdFile, ap_return_5_preg, "ap_return_5_preg");
    sc_trace(mVcdFile, ap_return_6_preg, "ap_return_6_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

master_ip_mainFunction::~master_ip_mainFunction() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_master_ip_get_gps_info_from_ubx_fu_166;
    delete call_ret6_master_ip_uart_to_byte_fu_183;
}

void master_ip_mainFunction::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
            ap_return_0_preg = uart_to_coordinates_ck_a_V_phi_fu_142_p4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
            ap_return_1_preg = uart_to_coordinates_ck_b_V_phi_fu_151_p4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_2_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
            ap_return_2_preg = uart_to_coordinates_current_ou_reg_459.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_3_preg = ap_const_lv6_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
            ap_return_3_preg = uart_to_coordinates_gnss_state_phi_fu_160_p4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_4_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
            ap_return_4_preg = coordinates_phi_fu_115_p4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_5_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
            ap_return_5_preg = coordinates_1_phi_fu_124_p4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_6_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
             !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
            ap_return_6_preg = coordinates_2_phi_fu_133_p4.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        coordinates_1_reg_121 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(tmp_fu_199_p1.read(), ap_const_lv1_0))) {
        coordinates_1_reg_121 = p_read2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        coordinates_2_reg_130 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(tmp_fu_199_p1.read(), ap_const_lv1_0))) {
        coordinates_2_reg_130 = p_read5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        coordinates_reg_112 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(tmp_fu_199_p1.read(), ap_const_lv1_0))) {
        coordinates_reg_112 = p_read.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
            grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_ready.read())) {
            grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        uart_to_coordinates_ck_a_V_reg_139 = uart_to_coordinates_ck_a_V_1_i_reg_466.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(tmp_fu_199_p1.read(), ap_const_lv1_0))) {
        uart_to_coordinates_ck_a_V_reg_139 = uart_to_coordinates_ck_a_V_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        uart_to_coordinates_ck_b_V_reg_148 = uart_to_coordinates_ck_b_V_1_i_reg_472.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(tmp_fu_199_p1.read(), ap_const_lv1_0))) {
        uart_to_coordinates_ck_b_V_reg_148 = uart_to_coordinates_ck_b_V_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        uart_to_coordinates_gnss_state_reg_157 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(tmp_fu_199_p1.read(), ap_const_lv1_0))) {
        uart_to_coordinates_gnss_state_reg_157 = uart_to_coordinates_gnss_state_V_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_reg_455 = call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0.read();
        uart_to_coordinates_current_ou_reg_459 = call_ret6_master_ip_uart_to_byte_fu_183_ap_return_1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        uart_to_coordinates_ck_a_V_1_i_reg_466 = uart_to_coordinates_ck_a_V_1_i_fu_328_p3.read();
        uart_to_coordinates_ck_b_V_1_i_reg_472 = uart_to_coordinates_ck_b_V_1_i_fu_337_p3.read();
    }
}

void master_ip_mainFunction::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read()))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void master_ip_mainFunction::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void master_ip_mainFunction::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void master_ip_mainFunction::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        ap_return_0 = uart_to_coordinates_ck_a_V_phi_fu_142_p4.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void master_ip_mainFunction::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        ap_return_1 = uart_to_coordinates_ck_b_V_phi_fu_151_p4.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void master_ip_mainFunction::thread_ap_return_2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        ap_return_2 = uart_to_coordinates_current_ou_reg_459.read();
    } else {
        ap_return_2 = ap_return_2_preg.read();
    }
}

void master_ip_mainFunction::thread_ap_return_3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        ap_return_3 = uart_to_coordinates_gnss_state_phi_fu_160_p4.read();
    } else {
        ap_return_3 = ap_return_3_preg.read();
    }
}

void master_ip_mainFunction::thread_ap_return_4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        ap_return_4 = coordinates_phi_fu_115_p4.read();
    } else {
        ap_return_4 = ap_return_4_preg.read();
    }
}

void master_ip_mainFunction::thread_ap_return_5() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        ap_return_5 = coordinates_1_phi_fu_124_p4.read();
    } else {
        ap_return_5 = ap_return_5_preg.read();
    }
}

void master_ip_mainFunction::thread_ap_return_6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read())))) {
        ap_return_6 = coordinates_2_phi_fu_133_p4.read();
    } else {
        ap_return_6 = ap_return_6_preg.read();
    }
}

void master_ip_mainFunction::thread_ap_sig_bdd_148() {
    ap_sig_bdd_148 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void master_ip_mainFunction::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void master_ip_mainFunction::thread_ap_sig_bdd_89() {
    ap_sig_bdd_89 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void master_ip_mainFunction::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void master_ip_mainFunction::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_89.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void master_ip_mainFunction::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_148.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void master_ip_mainFunction::thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i() {
    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_i = uart_to_coordinates_count_V_i.read();
}

void master_ip_mainFunction::thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read() {
    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_input_V_read = input_V_read.read();
}

void master_ip_mainFunction::thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read() {
    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_current_out_byte_V_read = uart_to_coordinates_current_out_byte_V_read.read();
}

void master_ip_mainFunction::thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i() {
    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_i = uart_to_coordinates_next_out_byte_V_i.read();
}

void master_ip_mainFunction::thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i() {
    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_i = uart_to_coordinates_previous_input_V_i.read();
}

void master_ip_mainFunction::thread_call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i() {
    call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_i = uart_to_coordinates_uart_state_V_i.read();
}

void master_ip_mainFunction::thread_coordinates_1_phi_fu_124_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0))) {
        coordinates_1_phi_fu_124_p4 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_2.read();
    } else {
        coordinates_1_phi_fu_124_p4 = coordinates_1_reg_121.read();
    }
}

void master_ip_mainFunction::thread_coordinates_2_phi_fu_133_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0))) {
        coordinates_2_phi_fu_133_p4 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_3.read();
    } else {
        coordinates_2_phi_fu_133_p4 = coordinates_2_reg_130.read();
    }
}

void master_ip_mainFunction::thread_coordinates_phi_fu_115_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0))) {
        coordinates_phi_fu_115_p4 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_1.read();
    } else {
        coordinates_phi_fu_115_p4 = coordinates_reg_112.read();
    }
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_start_ap_start_reg.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_p_read1 = p_read.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_p_read4 = p_read2.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_p_read5 = p_read5.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_a_V_read = uart_to_coordinates_ck_a_V_1_i_reg_466.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_ck_b_V_read = uart_to_coordinates_ck_b_V_1_i_reg_472.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_current_out_byte_V_read = uart_to_coordinates_current_ou_reg_459.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_gnss_state_V_read = uart_to_coordinates_gnss_state_V_read.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_i = uart_to_coordinates_tempCoordinates_0_i.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_i = uart_to_coordinates_tempCoordinates_1_i.read();
}

void master_ip_mainFunction::thread_grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i() {
    grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_i = uart_to_coordinates_tempCoordinates_2_i.read();
}

void master_ip_mainFunction::thread_or_cond4_i_fu_226_p2() {
    or_cond4_i_fu_226_p2 = (tmp_86_i_fu_216_p2.read() & tmp_87_i_fu_221_p2.read());
}

void master_ip_mainFunction::thread_sel_tmp1_fu_251_p2() {
    sel_tmp1_fu_251_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3E.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3E);
}

void master_ip_mainFunction::thread_sel_tmp2_fu_256_p2() {
    sel_tmp2_fu_256_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3D.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3D);
}

void master_ip_mainFunction::thread_sel_tmp3_fu_261_p2() {
    sel_tmp3_fu_261_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3C);
}

void master_ip_mainFunction::thread_sel_tmp4_fu_266_p2() {
    sel_tmp4_fu_266_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3B.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3B);
}

void master_ip_mainFunction::thread_sel_tmp5_fu_271_p2() {
    sel_tmp5_fu_271_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3A.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3A);
}

void master_ip_mainFunction::thread_sel_tmp6_fu_276_p2() {
    sel_tmp6_fu_276_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_1);
}

void master_ip_mainFunction::thread_sel_tmp7_fu_281_p2() {
    sel_tmp7_fu_281_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_0);
}

void master_ip_mainFunction::thread_sel_tmp8_fu_322_p2() {
    sel_tmp8_fu_322_p2 = (tmp11_fu_316_p2.read() | tmp8_fu_298_p2.read());
}

void master_ip_mainFunction::thread_sel_tmp_fu_246_p2() {
    sel_tmp_fu_246_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3F);
}

void master_ip_mainFunction::thread_tmp10_fu_310_p2() {
    tmp10_fu_310_p2 = (sel_tmp1_fu_251_p2.read() | sel_tmp7_fu_281_p2.read());
}

void master_ip_mainFunction::thread_tmp11_fu_316_p2() {
    tmp11_fu_316_p2 = (tmp10_fu_310_p2.read() | tmp9_fu_304_p2.read());
}

void master_ip_mainFunction::thread_tmp6_fu_286_p2() {
    tmp6_fu_286_p2 = (sel_tmp5_fu_271_p2.read() | sel_tmp6_fu_276_p2.read());
}

void master_ip_mainFunction::thread_tmp7_fu_292_p2() {
    tmp7_fu_292_p2 = (sel_tmp4_fu_266_p2.read() | sel_tmp3_fu_261_p2.read());
}

void master_ip_mainFunction::thread_tmp8_fu_298_p2() {
    tmp8_fu_298_p2 = (tmp7_fu_292_p2.read() | tmp6_fu_286_p2.read());
}

void master_ip_mainFunction::thread_tmp9_fu_304_p2() {
    tmp9_fu_304_p2 = (sel_tmp_fu_246_p2.read() | sel_tmp2_fu_256_p2.read());
}

void master_ip_mainFunction::thread_tmp_85_i_fu_211_p2() {
    tmp_85_i_fu_211_p2 = (!tmp_i_fu_207_p2.read().is_01() || !uart_to_coordinates_ck_b_V_read.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_i_fu_207_p2.read()) + sc_biguint<8>(uart_to_coordinates_ck_b_V_read.read()));
}

void master_ip_mainFunction::thread_tmp_86_i_fu_216_p2() {
    tmp_86_i_fu_216_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_39.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) > sc_biguint<6>(ap_const_lv6_39));
}

void master_ip_mainFunction::thread_tmp_87_i_fu_221_p2() {
    tmp_87_i_fu_221_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) < sc_biguint<6>(ap_const_lv6_3C));
}

void master_ip_mainFunction::thread_tmp_fu_199_p1() {
    tmp_fu_199_p1 = call_ret6_master_ip_uart_to_byte_fu_183_ap_return_0.read();
}

void master_ip_mainFunction::thread_tmp_i_fu_207_p2() {
    tmp_i_fu_207_p2 = (!uart_to_coordinates_current_ou_reg_459.read().is_01() || !uart_to_coordinates_ck_a_V_read.read().is_01())? sc_lv<8>(): (sc_biguint<8>(uart_to_coordinates_current_ou_reg_459.read()) + sc_biguint<8>(uart_to_coordinates_ck_a_V_read.read()));
}

void master_ip_mainFunction::thread_uart_to_coordinates_ck_a_V_1_i_fu_328_p3() {
    uart_to_coordinates_ck_a_V_1_i_fu_328_p3 = (!sel_tmp8_fu_322_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp8_fu_322_p2.read()[0].to_bool())? uart_to_coordinates_ck_a_V_rea_fu_232_p3.read(): tmp_i_fu_207_p2.read());
}

void master_ip_mainFunction::thread_uart_to_coordinates_ck_a_V_phi_fu_142_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0))) {
        uart_to_coordinates_ck_a_V_phi_fu_142_p4 = uart_to_coordinates_ck_a_V_1_i_reg_466.read();
    } else {
        uart_to_coordinates_ck_a_V_phi_fu_142_p4 = uart_to_coordinates_ck_a_V_reg_139.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_ck_a_V_rea_fu_232_p3() {
    uart_to_coordinates_ck_a_V_rea_fu_232_p3 = (!or_cond4_i_fu_226_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond4_i_fu_226_p2.read()[0].to_bool())? uart_to_coordinates_ck_a_V_read.read(): ap_const_lv8_0);
}

void master_ip_mainFunction::thread_uart_to_coordinates_ck_b_V_1_i_fu_337_p3() {
    uart_to_coordinates_ck_b_V_1_i_fu_337_p3 = (!sel_tmp8_fu_322_p2.read()[0].is_01())? sc_lv<8>(): ((sel_tmp8_fu_322_p2.read()[0].to_bool())? uart_to_coordinates_ck_b_V_rea_fu_239_p3.read(): tmp_85_i_fu_211_p2.read());
}

void master_ip_mainFunction::thread_uart_to_coordinates_ck_b_V_phi_fu_151_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0))) {
        uart_to_coordinates_ck_b_V_phi_fu_151_p4 = uart_to_coordinates_ck_b_V_1_i_reg_472.read();
    } else {
        uart_to_coordinates_ck_b_V_phi_fu_151_p4 = uart_to_coordinates_ck_b_V_reg_148.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_ck_b_V_rea_fu_239_p3() {
    uart_to_coordinates_ck_b_V_rea_fu_239_p3 = (!or_cond4_i_fu_226_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond4_i_fu_226_p2.read()[0].to_bool())? uart_to_coordinates_ck_b_V_read.read(): ap_const_lv8_0);
}

void master_ip_mainFunction::thread_uart_to_coordinates_count_V_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld.read()))) {
        uart_to_coordinates_count_V_o = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o.read();
    } else {
        uart_to_coordinates_count_V_o = uart_to_coordinates_count_V_i.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_count_V_o_ap_vld() {
    uart_to_coordinates_count_V_o_ap_vld = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_count_V_o_ap_vld.read();
}

void master_ip_mainFunction::thread_uart_to_coordinates_gnss_state_phi_fu_160_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0))) {
        uart_to_coordinates_gnss_state_phi_fu_160_p4 = grp_master_ip_get_gps_info_from_ubx_fu_166_ap_return_0.read();
    } else {
        uart_to_coordinates_gnss_state_phi_fu_160_p4 = uart_to_coordinates_gnss_state_reg_157.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_next_out_byte_V_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld.read()))) {
        uart_to_coordinates_next_out_byte_V_o = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o.read();
    } else {
        uart_to_coordinates_next_out_byte_V_o = uart_to_coordinates_next_out_byte_V_i.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_next_out_byte_V_o_ap_vld() {
    uart_to_coordinates_next_out_byte_V_o_ap_vld = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_next_out_byte_V_o_ap_vld.read();
}

void master_ip_mainFunction::thread_uart_to_coordinates_previous_input_V_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld.read()))) {
        uart_to_coordinates_previous_input_V_o = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o.read();
    } else {
        uart_to_coordinates_previous_input_V_o = uart_to_coordinates_previous_input_V_i.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_previous_input_V_o_ap_vld() {
    uart_to_coordinates_previous_input_V_o_ap_vld = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_previous_input_V_o_ap_vld.read();
}

void master_ip_mainFunction::thread_uart_to_coordinates_tempCoordinates_0_o() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld.read())))) {
        uart_to_coordinates_tempCoordinates_0_o = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o.read();
    } else {
        uart_to_coordinates_tempCoordinates_0_o = uart_to_coordinates_tempCoordinates_0_i.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_tempCoordinates_0_o_ap_vld() {
    uart_to_coordinates_tempCoordinates_0_o_ap_vld = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_0_o_ap_vld.read();
}

void master_ip_mainFunction::thread_uart_to_coordinates_tempCoordinates_1_o() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld.read())))) {
        uart_to_coordinates_tempCoordinates_1_o = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o.read();
    } else {
        uart_to_coordinates_tempCoordinates_1_o = uart_to_coordinates_tempCoordinates_1_i.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_tempCoordinates_1_o_ap_vld() {
    uart_to_coordinates_tempCoordinates_1_o_ap_vld = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_1_o_ap_vld.read();
}

void master_ip_mainFunction::thread_uart_to_coordinates_tempCoordinates_2_o() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          !esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld.read())))) {
        uart_to_coordinates_tempCoordinates_2_o = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o.read();
    } else {
        uart_to_coordinates_tempCoordinates_2_o = uart_to_coordinates_tempCoordinates_2_i.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_tempCoordinates_2_o_ap_vld() {
    uart_to_coordinates_tempCoordinates_2_o_ap_vld = grp_master_ip_get_gps_info_from_ubx_fu_166_uart_to_coordinates_tempCoordinates_2_o_ap_vld.read();
}

void master_ip_mainFunction::thread_uart_to_coordinates_uart_state_V_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld.read()))) {
        uart_to_coordinates_uart_state_V_o = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o.read();
    } else {
        uart_to_coordinates_uart_state_V_o = uart_to_coordinates_uart_state_V_i.read();
    }
}

void master_ip_mainFunction::thread_uart_to_coordinates_uart_state_V_o_ap_vld() {
    uart_to_coordinates_uart_state_V_o_ap_vld = call_ret6_master_ip_uart_to_byte_fu_183_uart_to_coordinates_uart_state_V_o_ap_vld.read();
}

void master_ip_mainFunction::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(tmp_fu_199_p1.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else if ((!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && !esl_seteq<1,1,1>(tmp_fu_199_p1.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            if (!(!esl_seteq<1,1,1>(tmp_reg_455.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, grp_master_ip_get_gps_info_from_ubx_fu_166_ap_done.read()))) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

