// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "master_ip_get_gps_info_from_ubx.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic master_ip_get_gps_info_from_ubx::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic master_ip_get_gps_info_from_ubx::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> master_ip_get_gps_info_from_ubx::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> master_ip_get_gps_info_from_ubx::ap_ST_st2_fsm_1 = "10";
const sc_lv<3> master_ip_get_gps_info_from_ubx::ap_ST_st3_fsm_2 = "100";
const sc_lv<32> master_ip_get_gps_info_from_ubx::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> master_ip_get_gps_info_from_ubx::ap_const_lv1_1 = "1";
const sc_lv<1> master_ip_get_gps_info_from_ubx::ap_const_lv1_0 = "0";
const sc_lv<32> master_ip_get_gps_info_from_ubx::ap_const_lv32_1 = "1";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_0 = "000000";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_1 = "1";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_2 = "10";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_3 = "11";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_4 = "100";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_5 = "101";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_3A = "111010";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_10 = "10000";
const sc_lv<8> master_ip_get_gps_info_from_ubx::ap_const_lv8_B5 = "10110101";
const sc_lv<8> master_ip_get_gps_info_from_ubx::ap_const_lv8_62 = "1100010";
const sc_lv<8> master_ip_get_gps_info_from_ubx::ap_const_lv8_1 = "1";
const sc_lv<8> master_ip_get_gps_info_from_ubx::ap_const_lv8_6 = "110";
const sc_lv<8> master_ip_get_gps_info_from_ubx::ap_const_lv8_34 = "110100";
const sc_lv<8> master_ip_get_gps_info_from_ubx::ap_const_lv8_0 = "00000000";
const sc_lv<32> master_ip_get_gps_info_from_ubx::ap_const_lv32_4 = "100";
const sc_lv<32> master_ip_get_gps_info_from_ubx::ap_const_lv32_5 = "101";
const sc_lv<2> master_ip_get_gps_info_from_ubx::ap_const_lv2_0 = "00";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_1D = "11101";
const sc_lv<32> master_ip_get_gps_info_from_ubx::ap_const_lv32_7 = "111";
const sc_lv<7> master_ip_get_gps_info_from_ubx::ap_const_lv7_0 = "0000000";
const sc_lv<8> master_ip_get_gps_info_from_ubx::ap_const_lv8_5 = "101";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_11 = "10001";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_16 = "10110";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_15 = "10101";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_1A = "11010";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_19 = "11001";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_1E = "11110";
const sc_lv<6> master_ip_get_gps_info_from_ubx::ap_const_lv6_3B = "111011";
const sc_lv<3> master_ip_get_gps_info_from_ubx::ap_const_lv3_0 = "000";
const sc_lv<9> master_ip_get_gps_info_from_ubx::ap_const_lv9_130 = "100110000";
const sc_lv<9> master_ip_get_gps_info_from_ubx::ap_const_lv9_150 = "101010000";
const sc_lv<9> master_ip_get_gps_info_from_ubx::ap_const_lv9_170 = "101110000";
const sc_lv<32> master_ip_get_gps_info_from_ubx::ap_const_lv32_2 = "10";

master_ip_get_gps_info_from_ubx::master_ip_get_gps_info_from_ubx(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( uart_to_coordinates_gnss_state_reg_317 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( mrv_sel_fu_772_p3 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( mrv_sel1_fu_779_p3 );
    sensitive << ( ap_return_2_preg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( mrv_sel2_fu_786_p3 );
    sensitive << ( ap_return_3_preg );

    SC_METHOD(thread_ap_sig_bdd_115);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );

    SC_METHOD(thread_ap_sig_bdd_118);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );

    SC_METHOD(thread_ap_sig_bdd_121);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );

    SC_METHOD(thread_ap_sig_bdd_132);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_472);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_643);
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );
    sensitive << ( or_cond12_fu_613_p2 );

    SC_METHOD(thread_ap_sig_bdd_646);
    sensitive << ( or_cond11_fu_595_p2 );
    sensitive << ( or_cond12_fu_613_p2 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_132 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_472 );

    SC_METHOD(thread_grp_fu_334_p2);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );

    SC_METHOD(thread_icmp1_fu_535_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( tmp_50_fu_525_p4 );

    SC_METHOD(thread_icmp_fu_471_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( tmp_49_fu_461_p4 );

    SC_METHOD(thread_mrv_sel1_fu_779_p3);
    sensitive << ( p_read4 );
    sensitive << ( write_flag3_1_reg_237 );
    sensitive << ( coordinates_1_1_reg_277 );

    SC_METHOD(thread_mrv_sel2_fu_786_p3);
    sensitive << ( p_read5 );
    sensitive << ( write_flag3_1_reg_237 );
    sensitive << ( coordinates_2_1_reg_297 );

    SC_METHOD(thread_mrv_sel_fu_772_p3);
    sensitive << ( p_read1 );
    sensitive << ( write_flag3_1_reg_237 );
    sensitive << ( coordinates_0_1_reg_257 );

    SC_METHOD(thread_or_cond10_fu_577_p2);
    sensitive << ( tmp_22_fu_565_p2 );
    sensitive << ( tmp_23_fu_571_p2 );

    SC_METHOD(thread_or_cond11_fu_595_p2);
    sensitive << ( tmp_30_fu_583_p2 );
    sensitive << ( tmp_31_fu_589_p2 );

    SC_METHOD(thread_or_cond12_fu_613_p2);
    sensitive << ( tmp_38_fu_601_p2 );
    sensitive << ( tmp_39_fu_607_p2 );

    SC_METHOD(thread_or_cond13_fu_631_p2);
    sensitive << ( tmp_46_fu_619_p2 );
    sensitive << ( tmp_47_fu_625_p2 );

    SC_METHOD(thread_or_cond1_fu_377_p2);
    sensitive << ( tmp_1_fu_365_p2 );
    sensitive << ( tmp_2_fu_371_p2 );

    SC_METHOD(thread_or_cond2_fu_395_p2);
    sensitive << ( tmp_3_fu_383_p2 );
    sensitive << ( tmp_4_fu_389_p2 );

    SC_METHOD(thread_or_cond3_fu_413_p2);
    sensitive << ( tmp_5_fu_401_p2 );
    sensitive << ( tmp_6_fu_407_p2 );

    SC_METHOD(thread_or_cond4_fu_431_p2);
    sensitive << ( tmp_7_fu_419_p2 );
    sensitive << ( tmp_8_fu_425_p2 );

    SC_METHOD(thread_or_cond5_fu_449_p2);
    sensitive << ( tmp_9_fu_437_p2 );
    sensitive << ( tmp_10_fu_443_p2 );

    SC_METHOD(thread_or_cond6_fu_477_p2);
    sensitive << ( tmp_11_fu_455_p2 );
    sensitive << ( icmp_fu_471_p2 );

    SC_METHOD(thread_or_cond7_fu_495_p2);
    sensitive << ( tmp_13_fu_483_p2 );
    sensitive << ( tmp_14_fu_489_p2 );

    SC_METHOD(thread_or_cond8_fu_513_p2);
    sensitive << ( tmp_15_fu_501_p2 );
    sensitive << ( tmp_16_fu_507_p2 );

    SC_METHOD(thread_or_cond9_fu_553_p2);
    sensitive << ( tmp1_fu_547_p2 );
    sensitive << ( tmp_17_fu_519_p2 );

    SC_METHOD(thread_or_cond_fu_359_p2);
    sensitive << ( tmp_fu_347_p2 );
    sensitive << ( tmp_s_fu_353_p2 );

    SC_METHOD(thread_tmp1_fu_547_p2);
    sensitive << ( icmp1_fu_535_p2 );
    sensitive << ( tmp_18_fu_541_p2 );

    SC_METHOD(thread_tmp_10_fu_443_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );

    SC_METHOD(thread_tmp_11_fu_455_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );

    SC_METHOD(thread_tmp_13_fu_483_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );

    SC_METHOD(thread_tmp_14_fu_489_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );

    SC_METHOD(thread_tmp_15_fu_501_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );

    SC_METHOD(thread_tmp_16_fu_507_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );
    sensitive << ( uart_to_coordinates_ck_a_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );

    SC_METHOD(thread_tmp_17_fu_519_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );

    SC_METHOD(thread_tmp_18_fu_541_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );

    SC_METHOD(thread_tmp_19_fu_559_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );

    SC_METHOD(thread_tmp_1_fu_365_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );

    SC_METHOD(thread_tmp_21_fu_766_p2);
    sensitive << ( tmp_20_reg_194 );

    SC_METHOD(thread_tmp_22_fu_565_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );

    SC_METHOD(thread_tmp_23_fu_571_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );

    SC_METHOD(thread_tmp_24_fu_723_p1);
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );

    SC_METHOD(thread_tmp_25_fu_731_p3);
    sensitive << ( tmp_51_fu_727_p1 );

    SC_METHOD(thread_tmp_26_fu_743_p2);
    sensitive << ( tmp_27_cast_fu_739_p1 );

    SC_METHOD(thread_tmp_27_cast_fu_739_p1);
    sensitive << ( tmp_25_fu_731_p3 );

    SC_METHOD(thread_tmp_27_fu_753_p2);
    sensitive << ( tmp_24_fu_723_p1 );
    sensitive << ( tmp_28_cast_fu_749_p1 );

    SC_METHOD(thread_tmp_28_cast_fu_749_p1);
    sensitive << ( tmp_26_fu_743_p2 );

    SC_METHOD(thread_tmp_28_fu_759_p2);
    sensitive << ( uart_to_coordinates_tempCoordinates_0_i );
    sensitive << ( tmp_27_fu_753_p2 );

    SC_METHOD(thread_tmp_2_fu_371_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );
    sensitive << ( or_cond_fu_359_p2 );

    SC_METHOD(thread_tmp_30_fu_583_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );

    SC_METHOD(thread_tmp_31_fu_589_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );

    SC_METHOD(thread_tmp_32_fu_680_p1);
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );

    SC_METHOD(thread_tmp_33_fu_688_p3);
    sensitive << ( tmp_52_fu_684_p1 );

    SC_METHOD(thread_tmp_34_fu_700_p2);
    sensitive << ( tmp_36_cast_fu_696_p1 );

    SC_METHOD(thread_tmp_35_fu_710_p2);
    sensitive << ( tmp_32_fu_680_p1 );
    sensitive << ( tmp_37_cast_fu_706_p1 );

    SC_METHOD(thread_tmp_36_cast_fu_696_p1);
    sensitive << ( tmp_33_fu_688_p3 );

    SC_METHOD(thread_tmp_36_fu_716_p2);
    sensitive << ( uart_to_coordinates_tempCoordinates_1_i );
    sensitive << ( tmp_35_fu_710_p2 );

    SC_METHOD(thread_tmp_37_cast_fu_706_p1);
    sensitive << ( tmp_34_fu_700_p2 );

    SC_METHOD(thread_tmp_38_fu_601_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );

    SC_METHOD(thread_tmp_39_fu_607_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );

    SC_METHOD(thread_tmp_3_fu_383_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );

    SC_METHOD(thread_tmp_40_fu_637_p1);
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );

    SC_METHOD(thread_tmp_41_fu_645_p3);
    sensitive << ( tmp_53_fu_641_p1 );

    SC_METHOD(thread_tmp_42_fu_657_p2);
    sensitive << ( tmp_45_cast_fu_653_p1 );

    SC_METHOD(thread_tmp_43_fu_667_p2);
    sensitive << ( tmp_40_fu_637_p1 );
    sensitive << ( tmp_46_cast_fu_663_p1 );

    SC_METHOD(thread_tmp_44_fu_673_p2);
    sensitive << ( uart_to_coordinates_tempCoordinates_2_i );
    sensitive << ( tmp_43_fu_667_p2 );

    SC_METHOD(thread_tmp_45_cast_fu_653_p1);
    sensitive << ( tmp_41_fu_645_p3 );

    SC_METHOD(thread_tmp_46_cast_fu_663_p1);
    sensitive << ( tmp_42_fu_657_p2 );

    SC_METHOD(thread_tmp_46_fu_619_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );
    sensitive << ( or_cond12_fu_613_p2 );

    SC_METHOD(thread_tmp_47_fu_625_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );
    sensitive << ( uart_to_coordinates_ck_b_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );
    sensitive << ( or_cond12_fu_613_p2 );

    SC_METHOD(thread_tmp_49_fu_461_p4);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );

    SC_METHOD(thread_tmp_4_fu_389_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );

    SC_METHOD(thread_tmp_50_fu_525_p4);
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );

    SC_METHOD(thread_tmp_51_fu_727_p1);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );

    SC_METHOD(thread_tmp_52_fu_684_p1);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );

    SC_METHOD(thread_tmp_53_fu_641_p1);
    sensitive << ( uart_to_coordinates_gnss_state_V_read );

    SC_METHOD(thread_tmp_5_fu_401_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );

    SC_METHOD(thread_tmp_6_fu_407_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );

    SC_METHOD(thread_tmp_7_fu_419_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );

    SC_METHOD(thread_tmp_8_fu_425_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );

    SC_METHOD(thread_tmp_9_fu_437_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );

    SC_METHOD(thread_tmp_fu_347_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_gnss_state_V_read );

    SC_METHOD(thread_tmp_s_fu_353_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( uart_to_coordinates_current_out_byte_V_read );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_0_o);
    sensitive << ( uart_to_coordinates_tempCoordinates_0_i );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( tmp_28_fu_759_p2 );
    sensitive << ( ap_sig_bdd_643 );
    sensitive << ( ap_sig_bdd_115 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_0_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );
    sensitive << ( or_cond12_fu_613_p2 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_1_o);
    sensitive << ( uart_to_coordinates_tempCoordinates_1_i );
    sensitive << ( or_cond11_fu_595_p2 );
    sensitive << ( tmp_36_fu_716_p2 );
    sensitive << ( ap_sig_bdd_646 );
    sensitive << ( ap_sig_bdd_118 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_1_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );
    sensitive << ( or_cond12_fu_613_p2 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_2_o);
    sensitive << ( uart_to_coordinates_tempCoordinates_2_i );
    sensitive << ( or_cond12_fu_613_p2 );
    sensitive << ( tmp_44_fu_673_p2 );
    sensitive << ( ap_sig_bdd_121 );

    SC_METHOD(thread_uart_to_coordinates_tempCoordinates_2_o_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );
    sensitive << ( or_cond10_fu_577_p2 );
    sensitive << ( or_cond11_fu_595_p2 );
    sensitive << ( or_cond12_fu_613_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( or_cond_fu_359_p2 );
    sensitive << ( or_cond1_fu_377_p2 );
    sensitive << ( or_cond2_fu_395_p2 );
    sensitive << ( or_cond3_fu_413_p2 );
    sensitive << ( or_cond4_fu_431_p2 );
    sensitive << ( or_cond5_fu_449_p2 );
    sensitive << ( or_cond6_fu_477_p2 );
    sensitive << ( or_cond7_fu_495_p2 );
    sensitive << ( or_cond8_fu_513_p2 );
    sensitive << ( or_cond9_fu_553_p2 );
    sensitive << ( tmp_19_fu_559_p2 );

    ap_CS_fsm = "001";
    ap_return_0_preg = "000000";
    ap_return_1_preg = "00000000000000000000000000000000";
    ap_return_2_preg = "00000000000000000000000000000000";
    ap_return_3_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "master_ip_get_gps_info_from_ubx_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, uart_to_coordinates_current_out_byte_V_read, "(port)uart_to_coordinates_current_out_byte_V_read");
    sc_trace(mVcdFile, uart_to_coordinates_gnss_state_V_read, "(port)uart_to_coordinates_gnss_state_V_read");
    sc_trace(mVcdFile, uart_to_coordinates_ck_a_V_read, "(port)uart_to_coordinates_ck_a_V_read");
    sc_trace(mVcdFile, uart_to_coordinates_ck_b_V_read, "(port)uart_to_coordinates_ck_b_V_read");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_0_i, "(port)uart_to_coordinates_tempCoordinates_0_i");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_0_o, "(port)uart_to_coordinates_tempCoordinates_0_o");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_0_o_ap_vld, "(port)uart_to_coordinates_tempCoordinates_0_o_ap_vld");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_1_i, "(port)uart_to_coordinates_tempCoordinates_1_i");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_1_o, "(port)uart_to_coordinates_tempCoordinates_1_o");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_1_o_ap_vld, "(port)uart_to_coordinates_tempCoordinates_1_o_ap_vld");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_2_i, "(port)uart_to_coordinates_tempCoordinates_2_i");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_2_o, "(port)uart_to_coordinates_tempCoordinates_2_o");
    sc_trace(mVcdFile, uart_to_coordinates_tempCoordinates_2_o_ap_vld, "(port)uart_to_coordinates_tempCoordinates_2_o_ap_vld");
    sc_trace(mVcdFile, p_read1, "(port)p_read1");
    sc_trace(mVcdFile, p_read4, "(port)p_read4");
    sc_trace(mVcdFile, p_read5, "(port)p_read5");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, grp_fu_334_p2, "grp_fu_334_p2");
    sc_trace(mVcdFile, or_cond_fu_359_p2, "or_cond_fu_359_p2");
    sc_trace(mVcdFile, or_cond1_fu_377_p2, "or_cond1_fu_377_p2");
    sc_trace(mVcdFile, or_cond2_fu_395_p2, "or_cond2_fu_395_p2");
    sc_trace(mVcdFile, or_cond3_fu_413_p2, "or_cond3_fu_413_p2");
    sc_trace(mVcdFile, or_cond4_fu_431_p2, "or_cond4_fu_431_p2");
    sc_trace(mVcdFile, or_cond5_fu_449_p2, "or_cond5_fu_449_p2");
    sc_trace(mVcdFile, or_cond6_fu_477_p2, "or_cond6_fu_477_p2");
    sc_trace(mVcdFile, or_cond7_fu_495_p2, "or_cond7_fu_495_p2");
    sc_trace(mVcdFile, or_cond8_fu_513_p2, "or_cond8_fu_513_p2");
    sc_trace(mVcdFile, or_cond9_fu_553_p2, "or_cond9_fu_553_p2");
    sc_trace(mVcdFile, tmp_19_fu_559_p2, "tmp_19_fu_559_p2");
    sc_trace(mVcdFile, or_cond10_fu_577_p2, "or_cond10_fu_577_p2");
    sc_trace(mVcdFile, or_cond11_fu_595_p2, "or_cond11_fu_595_p2");
    sc_trace(mVcdFile, or_cond12_fu_613_p2, "or_cond12_fu_613_p2");
    sc_trace(mVcdFile, or_cond13_fu_631_p2, "or_cond13_fu_631_p2");
    sc_trace(mVcdFile, tmp_21_fu_766_p2, "tmp_21_fu_766_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_132, "ap_sig_bdd_132");
    sc_trace(mVcdFile, tmp_20_reg_194, "tmp_20_reg_194");
    sc_trace(mVcdFile, write_flag3_1_reg_237, "write_flag3_1_reg_237");
    sc_trace(mVcdFile, coordinates_0_1_reg_257, "coordinates_0_1_reg_257");
    sc_trace(mVcdFile, coordinates_1_1_reg_277, "coordinates_1_1_reg_277");
    sc_trace(mVcdFile, coordinates_2_1_reg_297, "coordinates_2_1_reg_297");
    sc_trace(mVcdFile, uart_to_coordinates_gnss_state_reg_317, "uart_to_coordinates_gnss_state_reg_317");
    sc_trace(mVcdFile, tmp_28_fu_759_p2, "tmp_28_fu_759_p2");
    sc_trace(mVcdFile, tmp_36_fu_716_p2, "tmp_36_fu_716_p2");
    sc_trace(mVcdFile, tmp_44_fu_673_p2, "tmp_44_fu_673_p2");
    sc_trace(mVcdFile, tmp_fu_347_p2, "tmp_fu_347_p2");
    sc_trace(mVcdFile, tmp_s_fu_353_p2, "tmp_s_fu_353_p2");
    sc_trace(mVcdFile, tmp_1_fu_365_p2, "tmp_1_fu_365_p2");
    sc_trace(mVcdFile, tmp_2_fu_371_p2, "tmp_2_fu_371_p2");
    sc_trace(mVcdFile, tmp_3_fu_383_p2, "tmp_3_fu_383_p2");
    sc_trace(mVcdFile, tmp_4_fu_389_p2, "tmp_4_fu_389_p2");
    sc_trace(mVcdFile, tmp_5_fu_401_p2, "tmp_5_fu_401_p2");
    sc_trace(mVcdFile, tmp_6_fu_407_p2, "tmp_6_fu_407_p2");
    sc_trace(mVcdFile, tmp_7_fu_419_p2, "tmp_7_fu_419_p2");
    sc_trace(mVcdFile, tmp_8_fu_425_p2, "tmp_8_fu_425_p2");
    sc_trace(mVcdFile, tmp_9_fu_437_p2, "tmp_9_fu_437_p2");
    sc_trace(mVcdFile, tmp_10_fu_443_p2, "tmp_10_fu_443_p2");
    sc_trace(mVcdFile, tmp_49_fu_461_p4, "tmp_49_fu_461_p4");
    sc_trace(mVcdFile, tmp_11_fu_455_p2, "tmp_11_fu_455_p2");
    sc_trace(mVcdFile, icmp_fu_471_p2, "icmp_fu_471_p2");
    sc_trace(mVcdFile, tmp_13_fu_483_p2, "tmp_13_fu_483_p2");
    sc_trace(mVcdFile, tmp_14_fu_489_p2, "tmp_14_fu_489_p2");
    sc_trace(mVcdFile, tmp_15_fu_501_p2, "tmp_15_fu_501_p2");
    sc_trace(mVcdFile, tmp_16_fu_507_p2, "tmp_16_fu_507_p2");
    sc_trace(mVcdFile, tmp_50_fu_525_p4, "tmp_50_fu_525_p4");
    sc_trace(mVcdFile, icmp1_fu_535_p2, "icmp1_fu_535_p2");
    sc_trace(mVcdFile, tmp_18_fu_541_p2, "tmp_18_fu_541_p2");
    sc_trace(mVcdFile, tmp1_fu_547_p2, "tmp1_fu_547_p2");
    sc_trace(mVcdFile, tmp_17_fu_519_p2, "tmp_17_fu_519_p2");
    sc_trace(mVcdFile, tmp_22_fu_565_p2, "tmp_22_fu_565_p2");
    sc_trace(mVcdFile, tmp_23_fu_571_p2, "tmp_23_fu_571_p2");
    sc_trace(mVcdFile, tmp_30_fu_583_p2, "tmp_30_fu_583_p2");
    sc_trace(mVcdFile, tmp_31_fu_589_p2, "tmp_31_fu_589_p2");
    sc_trace(mVcdFile, tmp_38_fu_601_p2, "tmp_38_fu_601_p2");
    sc_trace(mVcdFile, tmp_39_fu_607_p2, "tmp_39_fu_607_p2");
    sc_trace(mVcdFile, tmp_46_fu_619_p2, "tmp_46_fu_619_p2");
    sc_trace(mVcdFile, tmp_47_fu_625_p2, "tmp_47_fu_625_p2");
    sc_trace(mVcdFile, tmp_53_fu_641_p1, "tmp_53_fu_641_p1");
    sc_trace(mVcdFile, tmp_41_fu_645_p3, "tmp_41_fu_645_p3");
    sc_trace(mVcdFile, tmp_45_cast_fu_653_p1, "tmp_45_cast_fu_653_p1");
    sc_trace(mVcdFile, tmp_42_fu_657_p2, "tmp_42_fu_657_p2");
    sc_trace(mVcdFile, tmp_40_fu_637_p1, "tmp_40_fu_637_p1");
    sc_trace(mVcdFile, tmp_46_cast_fu_663_p1, "tmp_46_cast_fu_663_p1");
    sc_trace(mVcdFile, tmp_43_fu_667_p2, "tmp_43_fu_667_p2");
    sc_trace(mVcdFile, tmp_52_fu_684_p1, "tmp_52_fu_684_p1");
    sc_trace(mVcdFile, tmp_33_fu_688_p3, "tmp_33_fu_688_p3");
    sc_trace(mVcdFile, tmp_36_cast_fu_696_p1, "tmp_36_cast_fu_696_p1");
    sc_trace(mVcdFile, tmp_34_fu_700_p2, "tmp_34_fu_700_p2");
    sc_trace(mVcdFile, tmp_32_fu_680_p1, "tmp_32_fu_680_p1");
    sc_trace(mVcdFile, tmp_37_cast_fu_706_p1, "tmp_37_cast_fu_706_p1");
    sc_trace(mVcdFile, tmp_35_fu_710_p2, "tmp_35_fu_710_p2");
    sc_trace(mVcdFile, tmp_51_fu_727_p1, "tmp_51_fu_727_p1");
    sc_trace(mVcdFile, tmp_25_fu_731_p3, "tmp_25_fu_731_p3");
    sc_trace(mVcdFile, tmp_27_cast_fu_739_p1, "tmp_27_cast_fu_739_p1");
    sc_trace(mVcdFile, tmp_26_fu_743_p2, "tmp_26_fu_743_p2");
    sc_trace(mVcdFile, tmp_24_fu_723_p1, "tmp_24_fu_723_p1");
    sc_trace(mVcdFile, tmp_28_cast_fu_749_p1, "tmp_28_cast_fu_749_p1");
    sc_trace(mVcdFile, tmp_27_fu_753_p2, "tmp_27_fu_753_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_472, "ap_sig_bdd_472");
    sc_trace(mVcdFile, mrv_sel_fu_772_p3, "mrv_sel_fu_772_p3");
    sc_trace(mVcdFile, mrv_sel1_fu_779_p3, "mrv_sel1_fu_779_p3");
    sc_trace(mVcdFile, mrv_sel2_fu_786_p3, "mrv_sel2_fu_786_p3");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_return_2_preg, "ap_return_2_preg");
    sc_trace(mVcdFile, ap_return_3_preg, "ap_return_3_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_643, "ap_sig_bdd_643");
    sc_trace(mVcdFile, ap_sig_bdd_115, "ap_sig_bdd_115");
    sc_trace(mVcdFile, ap_sig_bdd_646, "ap_sig_bdd_646");
    sc_trace(mVcdFile, ap_sig_bdd_118, "ap_sig_bdd_118");
    sc_trace(mVcdFile, ap_sig_bdd_121, "ap_sig_bdd_121");
#endif

    }
}

master_ip_get_gps_info_from_ubx::~master_ip_get_gps_info_from_ubx() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void master_ip_get_gps_info_from_ubx::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv6_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
            ap_return_0_preg = uart_to_coordinates_gnss_state_reg_317.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv32_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
            ap_return_1_preg = mrv_sel_fu_772_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_2_preg = ap_const_lv32_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
            ap_return_2_preg = mrv_sel1_fu_779_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_3_preg = ap_const_lv32_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
            ap_return_3_preg = mrv_sel2_fu_786_p3.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()))) {
        tmp_20_reg_194 = ap_const_lv6_10;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()))) {
        tmp_20_reg_194 = ap_const_lv6_3A;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()))) {
        tmp_20_reg_194 = ap_const_lv6_5;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()))) {
        tmp_20_reg_194 = ap_const_lv6_4;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()))) {
        tmp_20_reg_194 = ap_const_lv6_3;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()))) {
        tmp_20_reg_194 = ap_const_lv6_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()))) {
        tmp_20_reg_194 = ap_const_lv6_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                !esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0))) {
        tmp_20_reg_194 = ap_const_lv6_0;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read())))) {
        tmp_20_reg_194 = uart_to_coordinates_gnss_state_V_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read()))) {
        uart_to_coordinates_gnss_state_reg_317 = ap_const_lv6_0;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read())))) {
        uart_to_coordinates_gnss_state_reg_317 = grp_fu_334_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        uart_to_coordinates_gnss_state_reg_317 = tmp_21_fu_766_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read()))) {
        write_flag3_1_reg_237 = or_cond13_fu_631_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                 !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
                 esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read())) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        write_flag3_1_reg_237 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read()))) {
        coordinates_0_1_reg_257 = uart_to_coordinates_tempCoordinates_0_i.read();
        coordinates_1_1_reg_277 = uart_to_coordinates_tempCoordinates_1_i.read();
        coordinates_2_1_reg_297 = uart_to_coordinates_tempCoordinates_2_i.read();
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_return_0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        ap_return_0 = uart_to_coordinates_gnss_state_reg_317.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_return_1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        ap_return_1 = mrv_sel_fu_772_p3.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_return_2() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        ap_return_2 = mrv_sel1_fu_779_p3.read();
    } else {
        ap_return_2 = ap_return_2_preg.read();
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_return_3() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        ap_return_3 = mrv_sel2_fu_786_p3.read();
    } else {
        ap_return_3 = ap_return_3_preg.read();
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_bdd_115() {
    ap_sig_bdd_115 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()));
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_bdd_118() {
    ap_sig_bdd_118 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()));
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_bdd_121() {
    ap_sig_bdd_121 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()));
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_bdd_132() {
    ap_sig_bdd_132 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_bdd_472() {
    ap_sig_bdd_472 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_bdd_643() {
    ap_sig_bdd_643 = (esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read()));
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_bdd_646() {
    ap_sig_bdd_646 = (esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read()));
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_132.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_472.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_grp_fu_334_p2() {
    grp_fu_334_p2 = (!ap_const_lv6_1.is_01() || !uart_to_coordinates_gnss_state_V_read.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()));
}

void master_ip_get_gps_info_from_ubx::thread_icmp1_fu_535_p2() {
    icmp1_fu_535_p2 = (!tmp_50_fu_525_p4.read().is_01() || !ap_const_lv7_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_50_fu_525_p4.read() != ap_const_lv7_0);
}

void master_ip_get_gps_info_from_ubx::thread_icmp_fu_471_p2() {
    icmp_fu_471_p2 = (!tmp_49_fu_461_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_49_fu_461_p4.read() == ap_const_lv2_0);
}

void master_ip_get_gps_info_from_ubx::thread_mrv_sel1_fu_779_p3() {
    mrv_sel1_fu_779_p3 = (!write_flag3_1_reg_237.read()[0].is_01())? sc_lv<32>(): ((write_flag3_1_reg_237.read()[0].to_bool())? coordinates_1_1_reg_277.read(): p_read4.read());
}

void master_ip_get_gps_info_from_ubx::thread_mrv_sel2_fu_786_p3() {
    mrv_sel2_fu_786_p3 = (!write_flag3_1_reg_237.read()[0].is_01())? sc_lv<32>(): ((write_flag3_1_reg_237.read()[0].to_bool())? coordinates_2_1_reg_297.read(): p_read5.read());
}

void master_ip_get_gps_info_from_ubx::thread_mrv_sel_fu_772_p3() {
    mrv_sel_fu_772_p3 = (!write_flag3_1_reg_237.read()[0].is_01())? sc_lv<32>(): ((write_flag3_1_reg_237.read()[0].to_bool())? coordinates_0_1_reg_257.read(): p_read1.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond10_fu_577_p2() {
    or_cond10_fu_577_p2 = (tmp_22_fu_565_p2.read() & tmp_23_fu_571_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond11_fu_595_p2() {
    or_cond11_fu_595_p2 = (tmp_30_fu_583_p2.read() & tmp_31_fu_589_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond12_fu_613_p2() {
    or_cond12_fu_613_p2 = (tmp_38_fu_601_p2.read() & tmp_39_fu_607_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond13_fu_631_p2() {
    or_cond13_fu_631_p2 = (tmp_46_fu_619_p2.read() & tmp_47_fu_625_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond1_fu_377_p2() {
    or_cond1_fu_377_p2 = (tmp_1_fu_365_p2.read() & tmp_2_fu_371_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond2_fu_395_p2() {
    or_cond2_fu_395_p2 = (tmp_3_fu_383_p2.read() & tmp_4_fu_389_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond3_fu_413_p2() {
    or_cond3_fu_413_p2 = (tmp_5_fu_401_p2.read() & tmp_6_fu_407_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond4_fu_431_p2() {
    or_cond4_fu_431_p2 = (tmp_7_fu_419_p2.read() & tmp_8_fu_425_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond5_fu_449_p2() {
    or_cond5_fu_449_p2 = (tmp_9_fu_437_p2.read() & tmp_10_fu_443_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond6_fu_477_p2() {
    or_cond6_fu_477_p2 = (tmp_11_fu_455_p2.read() & icmp_fu_471_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond7_fu_495_p2() {
    or_cond7_fu_495_p2 = (tmp_13_fu_483_p2.read() & tmp_14_fu_489_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond8_fu_513_p2() {
    or_cond8_fu_513_p2 = (tmp_15_fu_501_p2.read() & tmp_16_fu_507_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond9_fu_553_p2() {
    or_cond9_fu_553_p2 = (tmp1_fu_547_p2.read() & tmp_17_fu_519_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_or_cond_fu_359_p2() {
    or_cond_fu_359_p2 = (tmp_fu_347_p2.read() & tmp_s_fu_353_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp1_fu_547_p2() {
    tmp1_fu_547_p2 = (icmp1_fu_535_p2.read() & tmp_18_fu_541_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_10_fu_443_p2() {
    tmp_10_fu_443_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_current_out_byte_V_read.read() == ap_const_lv8_0);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_11_fu_455_p2() {
    tmp_11_fu_455_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_5.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) > sc_biguint<6>(ap_const_lv6_5));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_13_fu_483_p2() {
    tmp_13_fu_483_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_1D.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) > sc_biguint<6>(ap_const_lv6_1D));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_14_fu_489_p2() {
    tmp_14_fu_489_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3A.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) < sc_biguint<6>(ap_const_lv6_3A));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_15_fu_501_p2() {
    tmp_15_fu_501_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3A.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3A);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_16_fu_507_p2() {
    tmp_16_fu_507_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !uart_to_coordinates_ck_a_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_current_out_byte_V_read.read() == uart_to_coordinates_ck_a_V_read.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_17_fu_519_p2() {
    tmp_17_fu_519_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_10.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_10);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_18_fu_541_p2() {
    tmp_18_fu_541_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !ap_const_lv8_5.is_01())? sc_lv<1>(): (sc_biguint<8>(uart_to_coordinates_current_out_byte_V_read.read()) < sc_biguint<8>(ap_const_lv8_5));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_19_fu_559_p2() {
    tmp_19_fu_559_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_11.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_11);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_1_fu_365_p2() {
    tmp_1_fu_365_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_1);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_21_fu_766_p2() {
    tmp_21_fu_766_p2 = (!tmp_20_reg_194.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_20_reg_194.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_22_fu_565_p2() {
    tmp_22_fu_565_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_11.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) > sc_biguint<6>(ap_const_lv6_11));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_23_fu_571_p2() {
    tmp_23_fu_571_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_16.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) < sc_biguint<6>(ap_const_lv6_16));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_24_fu_723_p1() {
    tmp_24_fu_723_p1 = esl_zext<32,8>(uart_to_coordinates_current_out_byte_V_read.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_25_fu_731_p3() {
    tmp_25_fu_731_p3 = esl_concat<5,3>(tmp_51_fu_727_p1.read(), ap_const_lv3_0);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_26_fu_743_p2() {
    tmp_26_fu_743_p2 = (!ap_const_lv9_170.is_01() || !tmp_27_cast_fu_739_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_170) + sc_biguint<9>(tmp_27_cast_fu_739_p1.read()));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_27_cast_fu_739_p1() {
    tmp_27_cast_fu_739_p1 = esl_zext<9,8>(tmp_25_fu_731_p3.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_27_fu_753_p2() {
    tmp_27_fu_753_p2 = (!tmp_28_cast_fu_749_p1.read().is_01())? sc_lv<32>(): tmp_24_fu_723_p1.read() << (unsigned short)tmp_28_cast_fu_749_p1.read().to_uint();
}

void master_ip_get_gps_info_from_ubx::thread_tmp_28_cast_fu_749_p1() {
    tmp_28_cast_fu_749_p1 = esl_sext<32,9>(tmp_26_fu_743_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_28_fu_759_p2() {
    tmp_28_fu_759_p2 = (uart_to_coordinates_tempCoordinates_0_i.read() | tmp_27_fu_753_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_2_fu_371_p2() {
    tmp_2_fu_371_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !ap_const_lv8_62.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_current_out_byte_V_read.read() == ap_const_lv8_62);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_30_fu_583_p2() {
    tmp_30_fu_583_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_15.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) > sc_biguint<6>(ap_const_lv6_15));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_31_fu_589_p2() {
    tmp_31_fu_589_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_1A.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) < sc_biguint<6>(ap_const_lv6_1A));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_32_fu_680_p1() {
    tmp_32_fu_680_p1 = esl_zext<32,8>(uart_to_coordinates_current_out_byte_V_read.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_33_fu_688_p3() {
    tmp_33_fu_688_p3 = esl_concat<5,3>(tmp_52_fu_684_p1.read(), ap_const_lv3_0);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_34_fu_700_p2() {
    tmp_34_fu_700_p2 = (!ap_const_lv9_150.is_01() || !tmp_36_cast_fu_696_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_150) + sc_biguint<9>(tmp_36_cast_fu_696_p1.read()));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_35_fu_710_p2() {
    tmp_35_fu_710_p2 = (!tmp_37_cast_fu_706_p1.read().is_01())? sc_lv<32>(): tmp_32_fu_680_p1.read() << (unsigned short)tmp_37_cast_fu_706_p1.read().to_uint();
}

void master_ip_get_gps_info_from_ubx::thread_tmp_36_cast_fu_696_p1() {
    tmp_36_cast_fu_696_p1 = esl_zext<9,8>(tmp_33_fu_688_p3.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_36_fu_716_p2() {
    tmp_36_fu_716_p2 = (uart_to_coordinates_tempCoordinates_1_i.read() | tmp_35_fu_710_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_37_cast_fu_706_p1() {
    tmp_37_cast_fu_706_p1 = esl_sext<32,9>(tmp_34_fu_700_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_38_fu_601_p2() {
    tmp_38_fu_601_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_19.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) > sc_biguint<6>(ap_const_lv6_19));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_39_fu_607_p2() {
    tmp_39_fu_607_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_1E.is_01())? sc_lv<1>(): (sc_biguint<6>(uart_to_coordinates_gnss_state_V_read.read()) < sc_biguint<6>(ap_const_lv6_1E));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_3_fu_383_p2() {
    tmp_3_fu_383_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_2.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_2);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_40_fu_637_p1() {
    tmp_40_fu_637_p1 = esl_zext<32,8>(uart_to_coordinates_current_out_byte_V_read.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_41_fu_645_p3() {
    tmp_41_fu_645_p3 = esl_concat<5,3>(tmp_53_fu_641_p1.read(), ap_const_lv3_0);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_42_fu_657_p2() {
    tmp_42_fu_657_p2 = (!ap_const_lv9_130.is_01() || !tmp_45_cast_fu_653_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_130) + sc_biguint<9>(tmp_45_cast_fu_653_p1.read()));
}

void master_ip_get_gps_info_from_ubx::thread_tmp_43_fu_667_p2() {
    tmp_43_fu_667_p2 = (!tmp_46_cast_fu_663_p1.read().is_01())? sc_lv<32>(): tmp_40_fu_637_p1.read() << (unsigned short)tmp_46_cast_fu_663_p1.read().to_uint();
}

void master_ip_get_gps_info_from_ubx::thread_tmp_44_fu_673_p2() {
    tmp_44_fu_673_p2 = (uart_to_coordinates_tempCoordinates_2_i.read() | tmp_43_fu_667_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_45_cast_fu_653_p1() {
    tmp_45_cast_fu_653_p1 = esl_zext<9,8>(tmp_41_fu_645_p3.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_46_cast_fu_663_p1() {
    tmp_46_cast_fu_663_p1 = esl_sext<32,9>(tmp_42_fu_657_p2.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_46_fu_619_p2() {
    tmp_46_fu_619_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3B.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3B);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_47_fu_625_p2() {
    tmp_47_fu_625_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !uart_to_coordinates_ck_b_V_read.read().is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_current_out_byte_V_read.read() == uart_to_coordinates_ck_b_V_read.read());
}

void master_ip_get_gps_info_from_ubx::thread_tmp_49_fu_461_p4() {
    tmp_49_fu_461_p4 = uart_to_coordinates_gnss_state_V_read.read().range(5, 4);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_4_fu_389_p2() {
    tmp_4_fu_389_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_current_out_byte_V_read.read() == ap_const_lv8_1);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_50_fu_525_p4() {
    tmp_50_fu_525_p4 = uart_to_coordinates_current_out_byte_V_read.read().range(7, 1);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_51_fu_727_p1() {
    tmp_51_fu_727_p1 = uart_to_coordinates_gnss_state_V_read.read().range(5-1, 0);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_52_fu_684_p1() {
    tmp_52_fu_684_p1 = uart_to_coordinates_gnss_state_V_read.read().range(5-1, 0);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_53_fu_641_p1() {
    tmp_53_fu_641_p1 = uart_to_coordinates_gnss_state_V_read.read().range(5-1, 0);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_5_fu_401_p2() {
    tmp_5_fu_401_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_3.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_3);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_6_fu_407_p2() {
    tmp_6_fu_407_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !ap_const_lv8_6.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_current_out_byte_V_read.read() == ap_const_lv8_6);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_7_fu_419_p2() {
    tmp_7_fu_419_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_4.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_4);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_8_fu_425_p2() {
    tmp_8_fu_425_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !ap_const_lv8_34.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_current_out_byte_V_read.read() == ap_const_lv8_34);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_9_fu_437_p2() {
    tmp_9_fu_437_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_5.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_5);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_fu_347_p2() {
    tmp_fu_347_p2 = (!uart_to_coordinates_gnss_state_V_read.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_gnss_state_V_read.read() == ap_const_lv6_0);
}

void master_ip_get_gps_info_from_ubx::thread_tmp_s_fu_353_p2() {
    tmp_s_fu_353_p2 = (!uart_to_coordinates_current_out_byte_V_read.read().is_01() || !ap_const_lv8_B5.is_01())? sc_lv<1>(): sc_lv<1>(uart_to_coordinates_current_out_byte_V_read.read() == ap_const_lv8_B5);
}

void master_ip_get_gps_info_from_ubx::thread_uart_to_coordinates_tempCoordinates_0_o() {
    if (ap_sig_bdd_115.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read())) {
            uart_to_coordinates_tempCoordinates_0_o = tmp_28_fu_759_p2.read();
        } else if (ap_sig_bdd_643.read()) {
            uart_to_coordinates_tempCoordinates_0_o = ap_const_lv32_0;
        } else {
            uart_to_coordinates_tempCoordinates_0_o = uart_to_coordinates_tempCoordinates_0_i.read();
        }
    } else {
        uart_to_coordinates_tempCoordinates_0_o = uart_to_coordinates_tempCoordinates_0_i.read();
    }
}

void master_ip_get_gps_info_from_ubx::thread_uart_to_coordinates_tempCoordinates_0_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read())))) {
        uart_to_coordinates_tempCoordinates_0_o_ap_vld = ap_const_logic_1;
    } else {
        uart_to_coordinates_tempCoordinates_0_o_ap_vld = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_uart_to_coordinates_tempCoordinates_1_o() {
    if (ap_sig_bdd_118.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read())) {
            uart_to_coordinates_tempCoordinates_1_o = tmp_36_fu_716_p2.read();
        } else if (ap_sig_bdd_646.read()) {
            uart_to_coordinates_tempCoordinates_1_o = ap_const_lv32_0;
        } else {
            uart_to_coordinates_tempCoordinates_1_o = uart_to_coordinates_tempCoordinates_1_i.read();
        }
    } else {
        uart_to_coordinates_tempCoordinates_1_o = uart_to_coordinates_tempCoordinates_1_i.read();
    }
}

void master_ip_get_gps_info_from_ubx::thread_uart_to_coordinates_tempCoordinates_1_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read())))) {
        uart_to_coordinates_tempCoordinates_1_o_ap_vld = ap_const_logic_1;
    } else {
        uart_to_coordinates_tempCoordinates_1_o_ap_vld = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_uart_to_coordinates_tempCoordinates_2_o() {
    if (ap_sig_bdd_121.read()) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read())) {
            uart_to_coordinates_tempCoordinates_2_o = tmp_44_fu_673_p2.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read())) {
            uart_to_coordinates_tempCoordinates_2_o = ap_const_lv32_0;
        } else {
            uart_to_coordinates_tempCoordinates_2_o = uart_to_coordinates_tempCoordinates_2_i.read();
        }
    } else {
        uart_to_coordinates_tempCoordinates_2_o = uart_to_coordinates_tempCoordinates_2_i.read();
    }
}

void master_ip_get_gps_info_from_ubx::thread_uart_to_coordinates_tempCoordinates_2_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond10_fu_577_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond11_fu_595_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_cond12_fu_613_p2.read())))) {
        uart_to_coordinates_tempCoordinates_2_o_ap_vld = ap_const_logic_1;
    } else {
        uart_to_coordinates_tempCoordinates_2_o_ap_vld = ap_const_logic_0;
    }
}

void master_ip_get_gps_info_from_ubx::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()))) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else if ((!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_19_fu_559_p2.read()) || 
  !esl_seteq<1,1,1>(or_cond_fu_359_p2.read(), ap_const_lv1_0) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond1_fu_377_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond2_fu_395_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond3_fu_413_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond4_fu_431_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond5_fu_449_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond6_fu_477_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond7_fu_495_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond8_fu_513_p2.read()) || 
  !esl_seteq<1,1,1>(ap_const_lv1_0, or_cond9_fu_553_p2.read())))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

